In [4]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')
# df.index.values

df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# 컬럼리스트 df.colums
df.columns

# df[컬럼이름]
# df['이름'] # 1개 출력 
# df[['이름','수학']] # 2개 이상 출력 [] 리스트 형태로 가져와야함

# df['이름':'과학'] # 슬라이싱 안됨  
# df[df.columns[0:4]] # colums 를 사용해서 슬라이싱 적용 
# df.loc[:,'이름':'수학'] # loc 를 사용해서 슬라이싱 가능 
# df.iloc[0:3] # index 에 해당되는 3개 출력 
# df[0:3] # index에 해당되는 3개 출력 

# df[df.columns[-1]] # 마지막 컬럼 출력 
# df[[df.columns[0,3,-1]]]

       이름    학교    키   국어
지원번호
1번    강나래   신림고  197   90
2번    강태원   신림고  184   40
3번    강호림   신림고  168   80
4번    김수찬   신림고  187   40
5번    김재욱   신림고  188   15
6번    박동현  디지털고  202   80
7번    박혜정  디지털고  188   55
8번    승근열  디지털고  190  100

In [19]:
# loc 출력 : 이름으로 출력 
# df['index 이름'], ['colums이름']
df.loc['1번']
df.loc[['1번', '2번']]
df.loc['1번':'5번']
df.loc['1번','이름':'수학'] # 슬라이싱 가능 
df.loc['2번':'5번','이름':'수학'] # 앞에 것은 인덱스에 있는 이름, 뒤에 있는 것은 컬럼에 있는 이름 
df.loc[['1번','2번'],'이름':'수학']

       이름   학교    키  국어  영어   수학  과학  사회    SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85  Python
2번    강태원  신림고  184  40  35   50  55  25    Java

In [25]:
# iloc 출력 : index에 있는 list 번호로 출력 
df.iloc[0]
df.iloc[0:4]
df.iloc[[0,1,4]]
df.iloc[0:4,1:5]
df.iloc[[1,5],1:5]

        학교    키  국어   영어
지원번호
2번     신림고  184  40   35
6번    디지털고  202  80  100

In [11]:
# 조건 : True, False 리턴
# df['키'] >= 185
# df[df['키'] >= 185]
# df[컬럼] >= 조건식
# df[df['국어'] >= 80]

df[df['사회'] >= 80]

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85  Python
4번    김수찬   신림고  187   40   60   70  75  80     NaN
6번    박동현  디지털고  202   80  100   95  85  80       C
8번    승근열  디지털고  190  100   85   90  95  95      C#

In [32]:
# df.loc[(index)row, colums]
df.loc[df['키']>190]

df.loc[df['키']>190, '이름':'수학'] # colums 사용해서 슬라이싱 가능

       이름    학교    키  국어   영어   수학
지원번호
1번    강나래   신림고  197  90   85  100
6번    박동현  디지털고  202  80  100   95

In [36]:
df.loc[(df['키']>185) & df['학교'=='디지털고'] ]
df.loc[(df['국어'] > 80) | (df['수학'] > 90)]

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85  Python
6번    박동현  디지털고  202   80  100   95  85  80       C
8번    승근열  디지털고  190  100   85   90  95  95      C#