In [1]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df.sort_index(ascending=True, inplace=True)

df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
df.describe() # 기본통계정보
df.info() # 각 칼럼

In [ ]:
# df['국어'].max()
# df.loc['1번']
df.loc['1번':'5번']

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85      Python
2번    강태원  신림고  184  40  35   50  55  25        Java
3번    강호림  신림고  168  80  75   70  80  75  Javascript
4번    김수찬  신림고  187  40  60   70  75  80         NaN
5번    김재욱  신림고  188  15  20   10  35  10         NaN

In [ ]:
df['키'].std() # 표준편차

np.float64(9.98570406702931)

In [68]:
# df.reset_index(inplace=True)
# df.reset_index(drop=True, inplace=True)
df.set_index('이름',inplace=True) # inplace = True 를 무조건 입력해야만 적용됨 
df
# df

       학교    키   국어   영어   수학  과학  사회        SW특기
이름
강나래   신림고  197   90   85  100  95  85      Python
강태원   신림고  184   40   35   50  55  25        Java
강호림   신림고  168   80   75   70  80  75  Javascript
김수찬   신림고  187   40   60   70  75  80         NaN
김재욱   신림고  188   15   20   10  35  10         NaN
박동현  디지털고  202   80  100   95  85  80           C
박혜정  디지털고  188   55   65   45  40  35      PYTHON
승근열  디지털고  190  100   85   90  95  95          C#

In [72]:
df.sort_index(ascending=False, inplace=True) # 순차정렬 : ascending=True, 역순정렬 : ascending=False
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
8번    승근열  디지털고  190  100   85   90  95  95          C#
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
6번    박동현  디지털고  202   80  100   95  85  80           C
5번    김재욱   신림고  188   15   20   10  35  10         NaN
4번    김수찬   신림고  187   40   60   70  75  80         NaN
3번    강호림   신림고  168   80   75   70  80  75  Javascript
2번    강태원   신림고  184   40   35   50  55  25        Java
1번    강나래   신림고  197   90   85  100  95  85      Python