In [3]:
import pandas as pd
import numpy as np
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# NaN 데이터 처리 - 결측치
# df.fillna('없음') # nan 데이터 체워줌 
# df.fillna('  ', inplace=True) # 공백으로 처리 
# df.fillna('X', inplace=True) # X로 처리 

# np.nam : num[u 명령어, nan 데이터를 모두 입력 
# numpy 는 숫자만 가능. 문자가 안됨 pandas 최신버젼 : float64버젼
df['학교'] = np.nan
df['학교'] = df['학교'].astype('object')
df.fillna('  ', inplace=True)
df.fillna('없음')
df

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래 NaN  197   90   85  100  95  85      Python
2번    강태원 NaN  184   40   35   50  55  25        Java
3번    강호림 NaN  168   80   75   70  80  75  Javascript
4번    김수찬 NaN  187   40   60   70  75  80         NaN
5번    김재욱 NaN  188   15   20   10  35  10         NaN
6번    박동현 NaN  202   80  100   95  85  80           C
7번    박혜정 NaN  188   55   65   45  40  35      PYTHON
8번    승근열 NaN  190  100   85   90  95  95          C#

In [33]:
# nan 데이터 삭제 : dropna 
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
# df['학교'] = df['학교'].astype('object')
# # df.fillna('  ', inplace=True)
df.dropna(inplace=True) # nan 이 포함되어진 모든 값을 다 지워줌

In [83]:
df = pd.read_excel('file/score.xlsx',index_col='지원번호') 
df['학교'] = np.nan    # pandas최신버전 : float64타입변경
df['학교'] = df['학교'].astype('object')

In [86]:
# df.fillna('없음',inplace=True)

# dropna : Nan데이터 삭제
# df.dropna(inplace=True)  # nan 있는 모든 row 삭제
# axis : index - 0, rows 가로삭제 ,columns - 1, column 세로삭제 
# how: any-1개만 있어도 삭제,all-모두있어야 삭제
# df.dropna(axis='index',how='any',inplace=True)      # 전체 삭제
# df.dropna(axis='index',how='all',inplace=True)    # 삭제 안됨
# df.dropna(axis='columns',how='any',inplace=True)    # SW특기 삭제
# df.dropna(axis='columns',how='all',inplace=True)    # 학교 삭제
df.dropna(axis=1,how='all',inplace=True)    # 학교 삭제

In [87]:
df

       이름    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래  197   90   85  100  95  85      Python
2번    강태원  184   40   35   50  55  25        Java
3번    강호림  168   80   75   70  80  75  Javascript
4번    김수찬  187   40   60   70  75  80         NaN
5번    김재욱  188   15   20   10  35  10         NaN
6번    박동현  202   80  100   95  85  80           C
7번    박혜정  188   55   65   45  40  35      PYTHON
8번    승근열  190  100   85   90  95  95          C#