In [22]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [24]:
# 문자열함수 str함수 - startswith:강으로 시작하는 문자열
# startswith,endswith,contains,lower,upper,capitalize
# replace - 대체
# split-분리,strip-공백제거,find-찾기,-1,len:글자수

# df[ df['이름'].str.startswith('강') ]
# df.loc[df['이름'].str.startswith('강')]

# contains 포함되어 있는 글자, ~ : not
# df[~df['이름'].str.contains('열')]

# lower,upper,capitalize
# df['SW특기']
# df['SW특기'].str.lower()
# df['SW특기'].str.upper()
# df['SW특기'].str.capitalize()

# # isin : 여러개 검색 ['python','java']
# langs = ['python','java']
# # df[df['SW특기'].str.lower().isin(langs)] #SW특기 값 소문자로 변경후 리스트검색

# # 
# # df['SW특기'].str.lower().contains()
# df['SW특기']
# df['SW특기'].str.contains('Java',na=False)
# df[df['SW특기'].str.contains('Java',na=True)]  #na=True : NaN 데이터 출력
# df[df['SW특기'].str.contains('Java',na=False)]  #na=False : NaN 출력하지 않음
# df[df['SW특기'].str.lower().str.contains('java',na=True)] # 소문자로 변경후 검색

# # unique 중복제거
# df['학교']
# df['학교'].unique()

langs = ['python', 'c', 'c#'] 
df[df['SW특기'].str.lower().isin(langs)]

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85  Python
6번    박동현  디지털고  202   80  100   95  85  80       C
7번    박혜정  디지털고  188   55   65   45  40  35  PYTHON
8번    승근열  디지털고  190  100   85   90  95  95      C#

### 문자열 .str
# startswith, lower,upper, capitalize, contains, endswith
# split, strip, find, len, replace, extract, cat, unique, nunique, 
#

In [26]:
# 문자열 함수 포함된 글자 찾기 
# df[df['이름'].str.startswith('강')]
# df.loc[df['이름'].str.startswith('강')]
df.loc[df['이름'].str.endswith('원')]

       이름   학교    키  국어  영어  수학  과학  사회  SW특기
지원번호
2번    강태원  신림고  184  40  35  50  55  25  Java

In [52]:
df = pd.read_excel('file/students.xlsx', index_col='번호')
# df[df['이름'].str.startswith('E')]
# df.loc[df['이름'].str.startswith('E')]
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [54]:

df['이름_첫두글자'] = df['이름'].str[:2]
df[['이름', '이름_첫두글자']]

            이름 이름_첫두글자
번호
1      Eadmund      Ea
2       Kirbee      Ki
3    Appolonia      Ap
4        Avery      Av
5       Dallis      Da
..         ...     ...
96        Luke      Lu
97        Nada      Na
98       Fiona      Fi
99        Leif      Le
100   Jonathan      Jo

[100 rows x 2 columns]

In [49]:
# unique 
df['학교'].unique()

<StringArray>
['신림고', '구로고', '디지털고']
Length: 3, dtype: str

In [56]:
df = pd.read_csv('file/drinks.csv')
df['continent'].unique()
df['continent'].nunique()

5

In [ ]:
df = pd.read_excel('file/연령별인구현황_2025.xlsx', skiprows=3)
# df.columns
# df
# 1개 일때는 str없이 사용, 여러 개일 str을 입력 휴 사용
# df.iloc[0,2] = df.iloc[0,2].replace(",", "") # 천 단위 표시 제거 후 다시 저장 
# df.iloc[0,2] 


df['총 인구수'] = df['총 인구수'].str.replace(",","").astype(int) # 전체 숫자로 되어진 문자열을 숫자타입으로 변환 하나만 변환 불가능 
df['총 인구수'] = df['총 인구수'].str.replace(",","").astype(int)

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

'51159889'

In [92]:
df = pd.read_excel('file/students.xlsx', index_col='번호')
# df
# 대문자 소문자 s가 있는 이름을 모두 출력하시오
# df.loc[df['이름'].str.startswith()('s')]

df[df['이름'].str.lower().str.contains('s')]

          이름    학교  학년    키  국어  영어  수학        SW특기
번호
5     Dallis  디지털고   1  209  97  57  76           C
14   Sibylle   구로고   1  197  82  81  38        JAVA
18     Mozes   신림고   1  176  61  44  51        JAVA
31    Holmes   구로고   1  184  51  21  87      Python
33  Robinson  디지털고   2  181  55  83  70      PYTHON
36   Ainslee  디지털고   2  201  66  15  89  Javascript
42  Sashenka  디지털고   2  195  69   7  55           c
44  Lisabeth   구로고   3  186  78  79  52           C
45      Mose   구로고   2  191  64  27  52
59   Kessiah  디지털고   2  162  66   0  67      PYTHON
62     Sheba  디지털고   1  184  88  90  67           c
63    Sarene   구로고   3  190  76  59  58      PYTHON
68     Tresa   구로고   2  166  58  37  70        java
73     Moise  디지털고   3  185  90  83  65        JAVA
74     Lewes  디지털고   2  187  61  22  43        JAVA
76    Dionis  디지털고   1  192  58  40  63  Javascript
80    Dallas   신림고   2  173  65  33  45      Python
89    Norris  디지털고   3  174  68   9  51        java

In [105]:
df = pd.read_excel('file/students.xlsx', index_col='번호')
# df['학교'] = df['학교'].str.replace("고","고등학교") # 글자 변경 (고 -> 고등학교)
# df['학교']

# df['학교'] = df['학교'].str.replace("고등학교","고") 
# df['학교'] = df['학교']+'등학교'

df['학교'] = df['학교'].str.replace("등","승")
df['학교'] = df['학교'].str.replace("승","등") 
df['학교']

번호
1       신림고
2       구로고
3       구로고
4       구로고
5      디지털고
       ...
96      신림고
97      구로고
98      신림고
99      구로고
100    디지털고
Name: 학교, Length: 100, dtype: str

In [125]:
df = pd.read_excel('file/students.xlsx',index_col='번호')
# df
# SW특기 java,c
langs = ['java','c']
df = df[df['SW특기'].str.lower().isin(langs)]['SW특기']
df.head(20)


# java가 포함되어 있는 글자를 모두 출력하시오.
# df[df['SW특기'].str.lower().str.contains('java',na=False)]

번호
1        c
2        C
3        C
4        C
5        C
8        C
13    JAVA
14    JAVA
16       c
17    JAVA
18    JAVA
22       c
34       C
42       c
44       C
49       C
52       c
54    java
55    JAVA
56    java
Name: SW특기, dtype: str