In [2]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# contains : 포함되어 있는 글자 찾기 
# df = pd.read_excel('file/score.xlsx', index_col='지원번호')
# # df[df['이름'].str.contains('원')]
# df[~df['이름'].str.contains('원')] # ~ 은 not 의 의미

# # lower(소문자), upper(대문자), capitalize (첫글자 대문자)
# df['SW특기'].str.lower()
# df['SW특기'].str.upper()
# df['SW특기'].str.capitalize()
# df[df['SW특기'].str.startswith('J')]

# # isin : 여러 개 검색 ['python', 'java']
# langs = ['python', 'java']
# df[df['SW특기'].str.lower().isin(langs)] # 소프트웨어특기에 있는 값을 소문자로 먼저 변경 후 리스트검색 

# contains 
# df[df['SW특기'].str.isin(langs)]
# df['SW특기'].str.contains('Java', na=False)
# df['SW특기'].str.contains('Java', na=False) # NaN 데이터 미 출력 
df[df['SW특기'].str.contains('Java', na=True)] # NaN 데이터 출력 
df['SW특기'].str.lower().str.contains('java', na=False) # 소문자로 변경후 검색 
df['SW특기'].str.lower().str.contains('java', na=True)

지원번호
1번    False
2번     True
3번     True
4번     True
5번     True
6번    False
7번    False
8번    False
Name: SW특기, dtype: bool

### 문자열 .str

In [25]:
# 문자열 함수 포함된 글자 찾기 
# df[df['이름'].str.startswith('강')]
df.loc[df['이름'].str.startswith('강')]

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85      Python
2번    강태원  신림고  184  40  35   50  55  25        Java
3번    강호림  신림고  168  80  75   70  80  75  Javascript

In [13]:
df = pd.read_excel('file/students.xlsx', index_col='번호')
df[df['이름'].str.startswith('E')]
df.loc[df['이름'].str.startswith('E')]

           이름   학교  학년    키  국어  영어  수학        SW특기
번호
1     Eadmund  신림고   2  171  56  92  60           c
20     Emelia  신림고   1  199  85  27  31  Javascript
21  Evangelia  신림고   2  190  51  71  83      PYTHON
55   Emmanuel  구로고   2  191  63  27  83        JAVA
88      Emile  신림고   2  199  83  26  68      PYTHON