In [22]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [11]:
# 데이터 수정 
df['학교'].replace({'구로고':'신림고', '디지털고':'사거리고'},inplace=True)
# df['학교'].str.replace({'신림고':'구로고'}) # str 문자열 변수이기에

C:\Users\mbc\AppData\Local\Temp\ipykernel_4468\315260093.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['학교'].replace({'구로고':'신림고', '디지털고':'사거리고'},inplace=True)

지원번호
1번     신림고
2번     신림고
3번     신림고
4번     신림고
5번     신림고
6번    사거리고
7번    사거리고
8번    사거리고
Name: 학교, dtype: str

In [ ]:
# df['학교'].replace({'구로고':'신림고', '디지털고':'사거리고'},inplace=True)
df['학교'] = df['학교'].replace({'구로고':'신림고', '디지털고':'사거리고'})
df.replace({'학교': {'구로고':'신림고', '디지털고':'사거리고'}},inplace=True)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  사거리고  202   80  100   95  85  80           C
7번    박혜정  사거리고  188   55   65   45  40  35      PYTHON
8번    승근열  사거리고  190  100   85   90  95  95          C#

In [75]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')

In [32]:
# 수정 
# df['학교'] = df['학교'] + '등학교'
# df['학교'] = df['학교'].str.replace('고', '고등학교')
# df['학교'] = df['학교'].str.replace('신림고', '포켓몬고')
# df['SW특기'] = df['SW특기'].str.lower()
# df['SW특기'] = df['SW특기'].str.upper()
df['SW특기'] = df['SW특기'].str.capitalize()

df

       이름          학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래  포켓몬고등학교등학교  197   90   85  100  95  85      Python
2번    강태원  포켓몬고등학교등학교  184   40   35   50  55  25        Java
3번    강호림  포켓몬고등학교등학교  168   80   75   70  80  75  Javascript
4번    김수찬  포켓몬고등학교등학교  187   40   60   70  75  80         NaN
5번    김재욱  포켓몬고등학교등학교  188   15   20   10  35  10         NaN
6번    박동현  디지털고등학교등학교  202   80  100   95  85  80           C
7번    박혜정  디지털고등학교등학교  188   55   65   45  40  35      Python
8번    승근열  디지털고등학교등학교  190  100   85   90  95  95          C#

# 데이터 추가 : 없는 컬럼값을 입력하면 추가가 됨

In [157]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')

In [158]:
# 데이터 추가 : 없는 컬럼값 입력하면 추가 가능 

df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
df['결과'] = '불합격' # 데이터 추가 

df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계   결과
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python  455  불합격
2번    강태원   신림고  184   40   35   50  55  25        Java  205  불합격
3번    강호림   신림고  168   80   75   70  80  75  Javascript  380  불합격
4번    김수찬   신림고  187   40   60   70  75  80         NaN  325  불합격
5번    김재욱   신림고  188   15   20   10  35  10         NaN   90  불합격
6번    박동현  디지털고  202   80  100   95  85  80           C  440  불합격
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240  불합격
8번    승근열  디지털고  190  100   85   90  95  95          C#  465  불합격

In [159]:

# 185 이상 출력하시오.
# df[df['키']>=185]
# 350점 이상

# 컬럼 전체를 수정할때 df['컬럼']
# df[df['합계']>=350]['결과'] = '합격'  
# df['국어'] = df['국어']+10
# 컬럼의 부분적인 값을 넣을때는 loc,iloc를 사용
df.loc[df['합계']>=350,'결과'] = '합격'  
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계   결과
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python  455   합격
2번    강태원   신림고  184   40   35   50  55  25        Java  205  불합격
3번    강호림   신림고  168   80   75   70  80  75  Javascript  380   합격
4번    김수찬   신림고  187   40   60   70  75  80         NaN  325  불합격
5번    김재욱   신림고  188   15   20   10  35  10         NaN   90  불합격
6번    박동현  디지털고  202   80  100   95  85  80           C  440   합격
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240  불합격
8번    승근열  디지털고  190  100   85   90  95  95          C#  465   합격

In [160]:
# 컬럼 데이터 삭제 : drop(columns 삭제)
# df.drop(columns=['합계'],inplace=True)
# df.drop(columns=['합계','결과'],inplace=True)

# index 데이터 삭제 : drop(index 삭제)
# df.drop(index='4번',inplace=True)

# df.columns # 전체컬럼 출력
# df.index # 전체index 출력
# 국어점수가 80점 이만 학생 삭제
filt = df['국어']<80
# df[filt].index
# df.drop(index=df[filt].index,inplace=True)
df[~filt].index
df.drop(index=df[~filt].index,inplace=True)

In [161]:
df

       이름    학교    키  국어  영어  수학  과학  사회    SW특기   합계   결과
지원번호
2번    강태원   신림고  184  40  35  50  55  25    Java  205  불합격
4번    김수찬   신림고  187  40  60  70  75  80     NaN  325  불합격
5번    김재욱   신림고  188  15  20  10  35  10     NaN   90  불합격
7번    박혜정  디지털고  188  55  65  45  40  35  PYTHON  240  불합격