In [29]:
import pandas as pd
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}
df = pd.DataFrame(data)
df.info()
# df

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   영화      8 non-null      str
 1   개봉 연도   8 non-null      int64
 2   관객 수    8 non-null      int64
 3   평점      8 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 388.0 bytes

In [ ]:
# 관객수 상위 5개만 출력하시오.
# 관객수 1,761    / 천단위 출력 '{:,d}'.format() #함수사용 
# 관객수 1761만명 / 만명 추가

# df.info()
# 1. 함수사용 - 천단위 표시

# def cal_change(x):
#     if pd.isna(x):  # 결측치(NaN) 처리 
#         return x
#     # return  f"{x:,}" : 숫자 전용 문법
#     # return  '{:,d}'.format() # 숫자를 문자변형
    
#     num = int(str(x).replace(",", "").split(".")[0])
#     return f"{num:,}"
    
# df["관객 수"] = df["관객 수"].apply(cal_change)
# df


#  2. lambda함수적용 
#  데이터를 숫자로 확실하게 변환
# df["관객 수"] = df["관객 수"].apply(lambda x: f"{int(str(x).replace(',', '')):,}")
# 결측치 예외 처리 포함
# df["관객 수"] = df["관객 수"].apply(lambda x: f"{int(str(x).replace(',', '')):,}" if pd.notna(x) else x)
# df

def cal(x):
    return x+2

#(lambda x : x+2) # 1줄 함수 
df

#  3. map사용
df['관객 수'] = df['관객 수'].map('{:,}'.format)

# 만명추가
# df['관객 수'] = df['관객 수'].astype(str)
df['관객 수'] = df['관객 수'] +'만명'
df

# 정수인데 문자로 튀는 이유 (판다스의 함정)
# 1. 결측치(NaN)가 숨어 있는 경우
# 데이터 중간에 빈 값(NaN)이 단 하나라도 섞여 있으면, 판다스는 원래 정수였던 컬럼을 실수(float64) 타입으로 강제로 바꿔버림 (예: 100이 100.0이 됨)
# 이 상태에서 .apply()로 값을 하나씩 꺼내다 보면, 판다스가 빈 값을 처리하는 과정이나 실수를 파이썬 함수로 넘길 때 파이썬 엔진이 이를 올바른 정수로 인식하지 못하고 타입 충돌을 일으킴
# 2. 판다스 고유의 스칼라 타입 문제
# 판다스가 .apply()를 돌릴 때 넘겨주는 값(x)은 순수 파이썬 정수(int)가 아니라 판다스/넘파이 내부의 특수한 숫자 객체(numpy.int64 등)인 경우가 많음
# 이 객체가 파이썬의 기본 f-string(f"{x:,}")을 만나는 찰나의 순간에, 판다스의 버전이나 데이터 결합 상태에 따라 파이썬이 이를 제대로 소화하지 못하고 포맷 에러를 뿜어내는 버그성 충돌이 발생

          영화  개봉 연도     관객 수    평점
0         명량   2014  1,761만명  8.88
1       극한직업   2019  1,626만명  9.20
2  신과함께-죄와 벌   2017  1,441만명  8.73
3       국제시장   2014  1,426만명  9.16
4         괴물   2006  1,301만명  8.62
5        도둑들   2012  1,298만명  7.64
6    7번방의 선물   2013  1,281만명  8.83
7         암살   2015  1,270만명  9.10

In [37]:
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}
df = pd.DataFrame(data)
# df.set_index('영화', inplace=True) 
df

          영화  개봉 연도  관객 수    평점
0         명량   2014  1761  8.88
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
3       국제시장   2014  1426  9.16
4         괴물   2006  1301  8.62
5        도둑들   2012  1298  7.64
6    7번방의 선물   2013  1281  8.83
7         암살   2015  1270  9.10

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   영화      8 non-null      str
 1   개봉 연도   8 non-null      int64
 2   관객 수    8 non-null      int64
 3   평점      8 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 388.0 bytes

In [ ]:
#  개봉연도 내림차순, 오름차순 으로 출력하시오.
# df.info()
df.sort_values('개봉 연도')
df['개봉 연도'].sort_values(ascending=True)
df['개봉 연도'].sort_values(ascending=False)

4    2006
5    2012
6    2013
0    2014
3    2014
7    2015
2    2017
1    2019
Name: 개봉 연도, dtype: int64

In [63]:
#  평점이 9점이상만 출력하시오.
flit = df['평점']>=9
df[flit]

     영화  개봉 연도  관객 수    평점
1  극한직업   2019  1626  9.20
3  국제시장   2014  1426  9.16
7    암살   2015  1270  9.10

In [66]:
#  평점 컬럼 내용에 8.88점 글자를 넣어서 출력하시오.
df['평점'] = df['평점'].astype(str)+'점'
df

          영화  개봉 연도  관객 수     평점
0         명량   2014  1761  8.88점
1       극한직업   2019  1626   9.2점
2  신과함께-죄와 벌   2017  1441  8.73점
3       국제시장   2014  1426  9.16점
4         괴물   2006  1301  8.62점
5        도둑들   2012  1298  7.64점
6    7번방의 선물   2013  1281  8.83점
7         암살   2015  1270   9.1점

In [64]:
# 평점중에 평점 평균이상인 row만 출력하시오.
flit = df['평점'] >= df['평점'].mean()
df[flit]

        영화  개봉 연도  관객 수    평점
0       명량   2014  1761  8.88
1     극한직업   2019  1626  9.20
3     국제시장   2014  1426  9.16
6  7번방의 선물   2013  1281  8.83
7       암살   2015  1270  9.10

In [67]:
# 2015년 이후에 개봉한 영화를 출력하시오.
flit = df['개봉 연도'] >= 2015
df[flit]

          영화  개봉 연도  관객 수     평점
1       극한직업   2019  1626   9.2점
2  신과함께-죄와 벌   2017  1441  8.73점
7         암살   2015  1270   9.1점