In [1]:
import pandas as pd
df=pd.read_excel('file/students.xlsx', index_col='번호')

# df

In [ ]:
# 합계 컬럼 추가
# SW특기 있으면 합계점수 5점 추가해서 입력하시오 
# 함수를 적용해서 처리하시오 

df['합계'] = df['국어'] + df['영어'] + df['수학'] 

def cal_sw(SW특기):
    if SW특기: 
        return 5
    else:
        return 0

df['가산점'] = df['SW특기'].apply(capChange)
df['합계'] = df['국어'] + df['영어'] + df['수학']+df['가산점'] 
df


df['합계'] = df['국어'] + df['영어'] + df['수학']
def cal_sw(df2):
    # if df2['SW특기'] != '':
    if pd.notnull(df2['SW특기']):
        return df2['합계']+5
    else:
        return df2['합계']
    
df['합계'] = df.apply(cal_sw,axis=1)
df

# null 비교 
# df['합계'] = df['국어'] + df['영어'] + df['수학']

# def cal_sw(lang):
#     if pd.notnull(lang): # null이 아니면 
#     # if lang != '':  
#         return lang.str.lower()
#     else:
#         return "없음"
# df['SW특기'] = df['SW특기'].apply(cal_sw)
# df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계  가산점
번호
1      Eadmund   신림고   2  171  56  92  60       c  208    5
2       Kirbee   구로고   1  199  53  10  45       C  108    5
3    Appolonia   구로고   3  193  77  52  81       C  210    5
4        Avery   구로고   2  187  59  35  43       C  137    5
5       Dallis  디지털고   1  209  97  57  76       C  230    5
..         ...   ...  ..  ...  ..  ..  ..     ...  ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213    5
97        Nada   구로고   3  170  60  89  55  PYTHON  204    5
98       Fiona   신림고   1  200  97  95  84       C  276    5
99        Leif   구로고   2  192  96  84  34  PYTHON  214    5
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227    5

[100 rows x 10 columns]

In [3]:
# 합계 컬럼 추가
df['합계'] = df['국어'] + df['영어'] + df['수학']
# SW특기 있으면 합계점수 5점을 추가해서 입력하시오.
# ( 함수를 사용해서 적용할 것 )
def cal_sw(df2):
    # if df2['SW특기'] != '':
    if pd.notnull(df2['SW특기']):
        return df2['합계']+5
    else:
        return df2['합계']
    
df['합계'] = df.apply(cal_sw,axis=1)
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계
번호
1      Eadmund   신림고   2  171  56  92  60       c  213
2       Kirbee   구로고   1  199  53  10  45       C  113
3    Appolonia   구로고   3  193  77  52  81       C  215
4        Avery   구로고   2  187  59  35  43       C  142
5       Dallis  디지털고   1  209  97  57  76       C  235
..         ...   ...  ..  ...  ..  ..  ..     ...  ...
96        Luke   신림고   3  187  91  63  59  Python  218
97        Nada   구로고   3  170  60  89  55  PYTHON  209
98       Fiona   신림고   1  200  97  95  84       C  281
99        Leif   구로고   2  192  96  84  34  PYTHON  219
100   Jonathan  디지털고   2  195  84  63  80    JAVA  232

[100 rows x 9 columns]