In [45]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')

# df.info()
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [41]:
# 컬럼전체 이름변경 
# 
# df['학교']=df['학교'].str.replace({'고등학교':'고교'})
df['학교']=df['학교'].str.replace({'구로고':'신림고'})
# df['학교']=df['학교'].replace({'중':'중학교'})
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [14]:
# 키 + cm 추가 
# df['키'] = df['키']+'cm' # 에러 남. # df['키']: int, 'cm: str 타입이라 에러 남 

# df['키'] = df['키'].astype(str)
# # df.info()
df['키'] = df['키'].astype(str)+'센치미터 '
df
# df['키'] = df['키']+100 # int+int 가능 
# df['키'] = df['키'].astype(str)   # str 타입으로 변경 
# df.info()
# 타입이 다른 경우 타입변경후 적용
# df['키'] = df['키'].astype(str)+'cm'
# df 

# apply 함수 적용하여 타입 변경 
# def add_cm(h):
#     return str(h)+'센티미터'

# df['키'] = df['키'].apply(add_cm)       
# df

       이름    학교         키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197센치미터    90   85  100  95  85      Python
2번    강태원   구로고  184센치미터    40   35   50  55  25        Java
3번    강호림   구로고  168센치미터    80   75   70  80  75  Javascript
4번    김수찬   구로고  187센치미터    40   60   70  75  80         NaN
5번    김재욱   구로고  188센치미터    15   20   10  35  10         NaN
6번    박동현  디지털고  202센치미터    80  100   95  85  80           C
7번    박혜정  디지털고  188센치미터    55   65   45  40  35      PYTHON
8번    승근열  디지털고  190센치미터   100   85   90  95  95          C#

In [17]:
df['SW특기']

지원번호
1번        Python
2번          Java
3번    Javascript
4번           NaN
5번           NaN
6번             C
7번        PYTHON
8번            C#
Name: SW특기, dtype: str

In [19]:
# 함수적용 
def capChange(lang):
    if pd.notnull(lang):  # 확인하는 기능 
        return lang.lower()
    # return lang
    return '특기없음'
# df['SW특기'].str.lower() # 소문자 변경 

# df['SW특기'] = df['SW특기'].apply(capChange) # NaN으로 인해 에러 남 
df['SW특기'] = df['SW특기'].apply(capChange)
df['SW특기']

지원번호
1번        python
2번          java
3번    javascript
4번          특기없음
5번          특기없음
6번             c
7번        python
8번            c#
Name: SW특기, dtype: str

In [18]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')

# 1. 합계 (과목총점을 계산해서) 컬럼을 추가하시오
# 2. 평균 컬럼을 추가하시오
# 3.등급 컬럼을 추가해서 90점 이상 A, 80점이상 B,70점 이상 C,60점 이상 D, 그 외에는 F를 입력하시오
# 함수를 사용해서 처리하시오

df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
df['평균'] = df['합계'] / 5
df['등급'] = 0 

df['score'] = df['평균']
def capChange(score):
    if score > 90: return 'A' 
    elif score > 80: return 'B' 
    elif score > 70: return 'C' 
    elif score > 60: return 'D' 
    else : return 'F'
    
df['등급'] = df['score'].apply(capChange)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계    평균 등급  score
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455  91.0  A   91.0
2번    강태원   구로고  184   40   35   50  55  25        Java  205  41.0  F   41.0
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380  76.0  C   76.0
4번    김수찬   구로고  187   40   60   70  75  80         NaN  325  65.0  D   65.0
5번    김재욱   구로고  188   15   20   10  35  10         NaN   90  18.0  F   18.0
6번    박동현  디지털고  202   80  100   95  85  80           C  440  88.0  B   88.0
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240  48.0  F   48.0
8번    승근열  디지털고  190  100   85   90  95  95          C#  465  93.0  A   93.0

In [22]:
# 합계에 등수를 만들어 줌 (ascending=False : 역순정렬 method='min' : 1,2,2,4로 출력. 같은 )
df['등수'] = df['합계'].rank(ascending=False).astype(int) # 합계에 등수를 만들어 줌
df

,이름,학교,키,국어,영어,수학,과학,사회,SW특기,합계,평균,등급,score,등수
지원번호,,,,,,,,,,,,,,
1번,강나래,구로고,197,90,85,100,95,85,Python,455,91.0,A,91.0,2
2번,강태원,구로고,184,40,35,50,55,25,Java,205,41.0,F,41.0,7
3번,강호림,구로고,168,80,75,70,80,75,Javascript,380,76.0,C,76.0,4
4번,김수찬,구로고,187,40,60,70,75,80,NaN,325,65.0,D,65.0,5
5번,김재욱,구로고,188,15,20,10,35,10,NaN,90,18.0,F,18.0,8
6번,박동현,디지털고,202,80,100,95,85,80,C,440,88.0,B,88.0,3
7번,박혜정,디지털고,188,55,65,45,40,35,PYTHON,240,48.0,F,48.0,6
8번,승근열,디지털고,190,100,85,90,95,95,C#,465,93.0,A,93.0,1

In [ ]:
df=pd.read_excel('file/students.xlsx', index_col='번호')
df['합계'] = df['국어']+df['영어']+df['수학']
df['평균'] = df['합계'] / 3
df.head(30)

           이름    학교  학년    키   국어  영어  수학        SW특기   합계         평균
번호
1     Eadmund   신림고   2  171   56  92  60           c  208  69.333333
2      Kirbee   구로고   1  199   53  10  45           C  108  36.000000
3   Appolonia   구로고   3  193   77  52  81           C  210  70.000000
4       Avery   구로고   2  187   59  35  43           C  137  45.666667
5      Dallis  디지털고   1  209   97  57  76           C  230  76.666667
6    Mitchell   구로고   3  197   81  95  30              206  68.666667
7        Gaye   신림고   3  192   65  27  86      PYTHON  178  59.333333
8         Rik  디지털고   1  199   80  93  31           C  204  68.000000
9       Jyoti   신림고   1  179  100   8  60              168  56.000000
10      Honor   신림고   2  186   83  11  58      PYTHON  152  50.666667
11       Mora  디지털고   1  166   74  29  89              192  64.000000
12     Lenora  디지털고   2  198   81  75  30      python  186  62.000000
13     Ardene  디지털고   2  161   91  97  33        JAVA  221  73.666667
14    Sibylle   구로고   1  197   82  81  38        JAVA  201  67.000000
15    Annette  디지털고   2  177   92  41  32      Python  165  55.000000
16   Marchall   구로고   2  202   83   4  79           c  166  55.333333
17      Alric   구로고   1  193   68  96  76        JAVA  240  80.000000
18      Mozes   신림고   1  176   61  44  51        JAVA  156  52.000000
19   Brigitta   구로고   2  175   54  61  73      PYTHON  188  62.666667
20     Emelia   신림고   1  199   85  27  31  Javascript  143  47.666667
21  Evangelia   신림고   2  190   51  71  83      PYTHON  205  68.333333
22       Abbe   구로고   1  188   72  65  86           c  223  74.333333
23       Jody   구로고   1  172   79  17  70              166  55.333333
24       Rici  디지털고   3  196   72  42  54      Python  168  56.000000
25      Robin   구로고   2  187   64  44  89      PYTHON  197  65.666667
26   Filberte  디지털고   2  194   66   0  39      python  105  35.000000
27     Gordan  디지털고   1  183   90  31  90      PYTHON  211  70.333333
28      Alard   신림고   1  178   96   1  48              145  48.333333
29    Timoteo   신림고   2  209   77  94  67      Python  238  79.333333
30     Urbain  디지털고   3  197   83  72  36  Javascript  191  63.666667

In [33]:
df = pd.read_excel('file/students.xlsx',index_col='번호')
df['합계'] = df['국어'] + df['영어'] + df['수학'] 
df['평균'] = df['합계'] / 3
df.drop(columns={'평균'},inplace=True)
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계
번호
1      Eadmund   신림고   2  171  56  92  60       c  208
2       Kirbee   구로고   1  199  53  10  45       C  108
3    Appolonia   구로고   3  193  77  52  81       C  210
4        Avery   구로고   2  187  59  35  43       C  137
5       Dallis  디지털고   1  209  97  57  76       C  230
..         ...   ...  ..  ...  ..  ..  ..     ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213
97        Nada   구로고   3  170  60  89  55  PYTHON  204
98       Fiona   신림고   1  200  97  95  84       C  276
99        Leif   구로고   2  192  96  84  34  PYTHON  214
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227

[100 rows x 9 columns]

In [ ]:
# method='min': 1,2,2,4 (default) / method='dense' 1,2,2,3
df['등수'] = df['합계'].rank(ascending=False, method='dense').astype(int)
df.sort_values('합계',ascending=False).head(30)

            이름    학교  학년    키  국어  영어  수학        SW특기   합계  등수
번호
77       Lorna   신림고   1  208  99  98  86      Python  283   1
98       Fiona   신림고   1  200  97  95  84           C  276   2
39         Ban   구로고   1  185  82  94  80      Python  256   3
34      Nollie  디지털고   1  197  84  89  78           C  251   4
62       Sheba  디지털고   1  184  88  90  67           c  245   5
81      Yancey   신림고   3  185  87  92  66      python  245   5
43        Dale   신림고   2  192  91  96  55      PYTHON  242   6
17       Alric   구로고   1  193  68  96  76        JAVA  240   7
52        Buck   신림고   2  187  93  71  75           c  239   8
73       Moise  디지털고   3  185  90  83  65        JAVA  238   9
29     Timoteo   신림고   2  209  77  94  67      Python  238   9
84         Ola  디지털고   3  170  84  77  77  Javascript  238   9
5       Dallis  디지털고   1  209  97  57  76           C  230  10
93       Kiele   구로고   3  193  68  99  62              229  11
100   Jonathan  디지털고   2  195  84  63  80        JAVA  227  12
58     Diahann   구로고   3  184  90  57  78           c  225  13
54         Ula   신림고   3  168  80  59  85        java  224  14
22        Abbe   구로고   1  188  72  65  86           c  223  15
13      Ardene  디지털고   2  161  91  97  33        JAVA  221  16
51   Madeleine  디지털고   1  177  86  55  78              219  17
47      Perkin  디지털고   2  169  82  73  62      python  217  18
65        Kiri   신림고   3  178  64  83  68        JAVA  215  19
32      Hamnet   신림고   3  171  95  55  65  Javascript  215  19
99        Leif   구로고   2  192  96  84  34      PYTHON  214  20
67    Filberto  디지털고   1  196  60  76  78           c  214  20
96        Luke   신림고   3  187  91  63  59      Python  213  21
27      Gordan  디지털고   1  183  90  31  90      PYTHON  211  22
3    Appolonia   구로고   3  193  77  52  81           C  210  23
44    Lisabeth   구로고   3  186  78  79  52           C  209  24
33    Robinson  디지털고   2  181  55  83  70      PYTHON  208  25