In [1]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [2]:
df.shape

(8, 9)

In [6]:
import random
for i in range(8):
    df.iloc[i,9] = random.randint(0,6)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기  요일
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python   0
2번    강태원   구로고  184   40   35   50  55  25        Java   0
3번    강호림   구로고  168   80   75   70  80  75  Javascript   1
4번    김수찬   구로고  187   40   60   70  75  80         NaN   6
5번    김재욱   구로고  188   15   20   10  35  10         NaN   2
6번    박동현  디지털고  202   80  100   95  85  80           C   5
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON   3
8번    승근열  디지털고  190  100   85   90  95  95          C#   1

In [5]:
df['요일'] = 0
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기  요일
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python   0
2번    강태원   구로고  184   40   35   50  55  25        Java   0
3번    강호림   구로고  168   80   75   70  80  75  Javascript   0
4번    김수찬   구로고  187   40   60   70  75  80         NaN   0
5번    김재욱   구로고  188   15   20   10  35  10         NaN   0
6번    박동현  디지털고  202   80  100   95  85  80           C   0
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON   0
8번    승근열  디지털고  190  100   85   90  95  95          C#   0

In [7]:
# 0-일요일,0-월요일,0-화요일,0-수요일,0-목요일,0-금요일,0-토요일 라고 출력하시오 

def cal_change(i):    
    if i == 0: return '일요일'
    elif i == 1: return '월요일'
    elif i == 2: return '화요일'
    elif i == 3: return '수요일'
    elif i == 4: return '목요일'
    elif i == 5: return '금요일'
    else : return '토요일'        

# df['요일'] = df['요일'].apply(cal_change)
# for i in range(7): 
df['요일'] = df['요일'].apply(cal_change)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   요일
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  일요일
2번    강태원   구로고  184   40   35   50  55  25        Java  일요일
3번    강호림   구로고  168   80   75   70  80  75  Javascript  월요일
4번    김수찬   구로고  187   40   60   70  75  80         NaN  토요일
5번    김재욱   구로고  188   15   20   10  35  10         NaN  화요일
6번    박동현  디지털고  202   80  100   95  85  80           C  금요일
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  수요일
8번    승근열  디지털고  190  100   85   90  95  95          C#  월요일

In [14]:
data = {
    '번호':['1번','2번','3번','4번','5번','6번','7번','8번'],
    '이름':['홍길동','유관순','이순신','강감찬','김구','김유신','홍길자','홍길순'],
    '달러':['$19,700','$18,400','$16,800','$18,700','$18,800','$20,200','$18,800','$19,000'],
    '우대':[90,40,80,40,15,80,55,100]
}

df = pd.DataFrame(data)
df.set_index('번호', inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   달러      8 non-null      str
 2   우대      8 non-null      int64
dtypes: int64(1), str(2)
memory usage: 256.0+ bytes

In [15]:
# 1. 금액컬럼을 추가하시오 (금액 : 달러 + 달러 우대 X 0.01)
# 2. 우대가 50 이상인 사람에게만 달러 + 달로 X 우대 X 0.01 
# 3. 50 미만은 달러만 입력 

df['금액'] = 0
# 우대가 50이상인 사람에게만 달러+달러*우대*0.01 
# 우대 50미만인 사람에게만 달러 

df['달러'] = df['달러'].str.replace('$','')
df['달러'] = df['달러'].str.replace(',','').str.strip().astype(int)
df

     이름     달러   우대  금액
번호
1번  홍길동  19700   90   0
2번  유관순  18400   40   0
3번  이순신  16800   80   0
4번  강감찬  18700   40   0
5번   김구  18800   15   0
6번  김유신  20200   80   0
7번  홍길자  18800   55   0
8번  홍길순  19000  100   0

In [18]:
# 2개가 넘어와야함. df['달러'], df['우대']

def cal_change(df2):
    if df2['우대']>=50:
        return df2['달러'] + (df2['달러'] * df2['우대'] * 0.01)
    else:
        return df2['달러']    

df['금액'] = df.apply(cal_change,axis=1)
df.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   달러      8 non-null      int64
 2   우대      8 non-null      int64
 3   금액      8 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 320.0+ bytes

In [31]:
df = pd.read_csv('file/jumin08_2.csv')
df2 = df[['행정구역', '2026년08월_총인구수']]
df3 = df2[1:6]
# df3
# df.columns
# df.info()

df3['2026년08월_총인구수'] = df3['2026년08월_총인구수'].str.replace(",","").astype(int)
df3.info()
df3['2026년08월_총인구수'].sum()


# df3['2026년08월_총인구수'] = df3['2026년08월_총인구수'].str.replace(",","").astype(int)
# # df3.info()
# df3.describe()
# df3['2026년08월_총인구수'].sum()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 1 to 5
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   행정구역           5 non-null      str
 1   2026년08월_총인구수  5 non-null      int64
dtypes: int64(1), str(1)
memory usage: 212.0 bytes

np.int64(21079357)

### 새로운 데이터가 생길경우 일단 파일 확인부터 해야함
### df. info(), df.describe() 등을 이용해서 확인부터 해야함
### 데이터 탐색기 함수 잘 이용하기