In [25]:
import pandas as pd
df = pd.read_excel('file/students.xlsx', index_col='번호')
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [19]:
# 합계, 평균,결과 컴럼을 추가
# 결과 평균점수가 70점 이상은 합격, 불합격으로 출력하시오.

df['합계'] = df['국어']+df['영어']+df['수학']
df['평균'] = df['합계'] / 3
df['결과'] = '불합격'

df.loc[df['평균'] > 70,  '결과'] = '합격'
df.loc[df['평균'] <= 70, '결과'] = '불합격'

df

# df['합격'] = df['국어']+df['영어']+df['수학']
# df['평균'] = df['합격'] / 3
# df['결과'] = "불합격"
# df.loc[df['평균'] > 70, '결과'] = '합격'
# df.loc[df['평균'] <= 70, '결과'] = '불합격'
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계         평균   결과
번호
1      Eadmund   신림고   2  171  56  92  60       c  208  69.333333  불합격
2       Kirbee   구로고   1  199  53  10  45       C  108  36.000000  불합격
3    Appolonia   구로고   3  193  77  52  81       C  210  70.000000  불합격
4        Avery   구로고   2  187  59  35  43       C  137  45.666667  불합격
5       Dallis  디지털고   1  209  97  57  76       C  230  76.666667   합격
..         ...   ...  ..  ...  ..  ..  ..     ...  ...        ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213  71.000000   합격
97        Nada   구로고   3  170  60  89  55  PYTHON  204  68.000000  불합격
98       Fiona   신림고   1  200  97  95  84       C  276  92.000000   합격
99        Leif   구로고   2  192  96  84  34  PYTHON  214  71.333333   합격
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227  75.666667   합격

[100 rows x 11 columns]

In [15]:
df.value_counts('결과') # 그룹으로 개수확인

결과
불합격    73
합격     27
Name: count, dtype: int64

In [21]:
# df2=df[['이름','평균','결과']]
# df2

# 컬럼 순서 변경 : 변경하고자 하는 컬럼명은 변경하고자 하는 부분에 입력하면 됨 
df3=df[['이름','합계','평균','결과','학교','학년','키','국어','영어','수학','SW특기']]
df3 

# df[[df.columns[0:3],df.columns[6:9]]] # 연이어서 입력하면 에러 남

            이름   합계         평균   결과    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund  208  69.333333  불합격   신림고   2  171  56  92  60       c
2       Kirbee  108  36.000000  불합격   구로고   1  199  53  10  45       C
3    Appolonia  210  70.000000  불합격   구로고   3  193  77  52  81       C
4        Avery  137  45.666667  불합격   구로고   2  187  59  35  43       C
5       Dallis  230  76.666667   합격  디지털고   1  209  97  57  76       C
..         ...  ...        ...  ...   ...  ..  ...  ..  ..  ..     ...
96        Luke  213  71.000000   합격   신림고   3  187  91  63  59  Python
97        Nada  204  68.000000  불합격   구로고   3  170  60  89  55  PYTHON
98       Fiona  276  92.000000   합격   신림고   1  200  97  95  84       C
99        Leif  214  71.333333   합격   구로고   2  192  96  84  34  PYTHON
100   Jonathan  227  75.666667   합격  디지털고   2  195  84  63  80    JAVA

[100 rows x 11 columns]

In [ ]:
import pandas as pd
df = pd.read_excel('file/students.xlsx', index_col='번호')
df
# colds 리스트 순서를 변경 
# 1. cols은 리스트 타입으로 변환 
cols = list(df.columns) # cols은 리스트 타입으로 변환 

# 2. 
cols[-2:] # 끝에서 두번째부터 출력 (평균,결과 컬럼)
cols[:-2] # 처음부터 끝에서 두번째 전까지 출력 (이름 ~ 합계)
cols[0]
cols[1:-2] # 1번부터 끝에서 두번째 전까지 출력 (학교 ~ 수학) # list 타입 
type(cols[0]) # str # 리스트 타입일 때만 덧셈 가능 
type(cols[1:-2]) # list 

# 3. 리스트 순서변경 
[cols[0]]+cols[-2:]+cols[1:-2] # str+#list+list => error / str에 대괄호 추가하면 가능 
# # 변경된 리스트 적용
df=df[cols]

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [51]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df

# rows : index 수정 / 삭제 / 추가 (rows)

# 1. index 삭제 : 조건사용해서 삭제 
df.loc[df['국어'] >= 80, '결과'] = "합격"
df.loc[df['국어'] < 80, '결과'] = "불합격"
# 수학점수가 80점 미만인 학생만 삭제 
flit = df['수학'] < 80
# df[flit]
df[~flit]

# df2=df[flit]
# df3=df[~flit]

# df = df.drop(columns=['평균','결과'], inplace=True) # 조건에 맞는 컬럼 삭제

df.drop(index=['1번','2번'], inplace=True) # 조건에 맞는 index 삭제
df

       이름    학교    키   국어   영어  수학  과학  사회        SW특기   결과
지원번호
3번    강호림   구로고  168   80   75  70  80  75  Javascript   합격
4번    김수찬   구로고  187   40   60  70  75  80         NaN  불합격
5번    김재욱   구로고  188   15   20  10  35  10         NaN  불합격
6번    박동현  디지털고  202   80  100  95  85  80           C   합격
7번    박혜정  디지털고  188   55   65  45  40  35      PYTHON  불합격
8번    승근열  디지털고  190  100   85  90  95  95          C#   합격

In [50]:
# [index row 삭제]
# df.drop(index=['1번','2번'], inplace=True) 
# df

# 조건을 이용한 index 삭제
flit = df['수학'] < 80
flit.index
df.drop(index=flit.index, inplace=True)
df

# df.drop(index=df[flit].index, inplace=True)
# df

Empty DataFrame
Columns: [이름, 학교, 키, 국어, 영어, 수학, 과학, 사회, SW특기, 결과]
Index: []

In [54]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
# df.columns

# 국어, 영어, 수학, 과학, 사회 점수 합계 컬럼 추가하고 합계 점수가 350이상만 출력하시오
# 합계 350미만 학생 삭제 

df['합계'] = df['국어'] + df['영어'] + df['수학'] + df['과학'] + df['사회']

# flit = df['합계'] > 350
# df[flit] # 350점 이상 학생만 출력

flit = df['합계'] >= 350
df.drop(df[~flit].index, inplace=True) # 350점 미만 학생 삭제
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380
6번    박동현  디지털고  202   80  100   95  85  80           C  440
8번    승근열  디지털고  190  100   85   90  95  95          C#  465

In [59]:
# index 추가 : loc 사용해서 컬럼 개수만큼 입력하면 됨 
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df.loc['9번'] = ['홍길동','구로고', '190',90, 80, 70, 60, 50, 'Python'] # index 추가

# SW특깁 부분 값 입력하면 추가 
df.loc['4번','SW특기'] = 'C' # index 추가
# df.loc['5번','SW특기'] = 'Java' # index 추가

# 학교컬럼, SW특기컬럼 값 수정하여 입력하면 추가 (부분수정)
# df.loc['4번',['학교', 'SW특기']] = ['디지털고','python']
df.loc['5번', ['학교','사회','SW특기']] = ['디지털고',50,'Java']
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80           C
5번    김재욱  디지털고  188   15   20   10  35  50        Java
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#
9번    홍길동   구로고  190   90   80   70  60  50      Python

In [63]:
# columns 이름 변경 
# df.columns = [변경할 이름 입력]
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
# df2 = df[['이름','국어','영어']]
# df2

# 부분 컬럼 이름 변경 
df.rename(columns={'이름':'name', '키':'hei','국어':'kor','영어':'eng','수학':'math','과학':'sci','사회':'soc','SW특기':'SWSP'},inplace=True)
df

# df.columns[1] = '학교' # 이 방법은 안 됨 
df.rename(columns={df.columns[1]:'school'},inplace=True)
df

     name school  hei  kor  eng  math  sci  soc        SWSP
지원번호
1번    강나래    구로고  197   90   85   100   95   85      Python
2번    강태원    구로고  184   40   35    50   55   25        Java
3번    강호림    구로고  168   80   75    70   80   75  Javascript
4번    김수찬    구로고  187   40   60    70   75   80         NaN
5번    김재욱    구로고  188   15   20    10   35   10         NaN
6번    박동현   디지털고  202   80  100    95   85   80           C
7번    박혜정   디지털고  188   55   65    45   40   35      PYTHON
8번    승근열   디지털고  190  100   85    90   95   95          C#