In [24]:
import pandas as pd
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}
df = pd.DataFrame(data)
# df.info()

In [ ]:
# 1. 함수사용 - 천단위 표시
def cal_change(x):
    return  f"{x:,}"
    # return  '{:,d}'.format() # 숫자를 문자변형

df['관객 수'] = df['관객 수'].apply(cal_change)

#  2. lambda함수적용
df['관객 수'] = df['관객 수'].apply(lambda x: f"{x:,}")
#  3. map사용
# df['관객 수'] = df['관객 수'].map('{:,}'.format)

          영화  개봉 연도   관객 수    평점
0         명량   2014  1,761  8.88
1       극한직업   2019  1,626  9.20
2  신과함께-죄와 벌   2017  1,441  8.73
3       국제시장   2014  1,426  9.16
4         괴물   2006  1,301  8.62
5        도둑들   2012  1,298  7.64
6    7번방의 선물   2013  1,281  8.83
7         암살   2015  1,270  9.10

In [ ]:
# 관객수 1761만명 출력 / 천단위 출력 '{:d}'.format() # 함수사용 
# 관객수 1,761만명 출력 
df['관객 수'] = df['관객 수'].astype(int)
df['관객 수']=df['관객 수']+'만명'
df['관객 수'] = df['관객 수'].astype(str) + '만명'

ValueError: invalid literal for int() with base 10: '1,761'

In [ ]:
# map 함수 
df['관객 수']=df['관객 수'].map('{:,}'.format) # 함수 한 개씩 가져와서 처리해줌 
# lambda 함수 
df['관객 수']=df['관객 수'].apply(lambda x: f"{x:},")
df

def cal(x):
    return x+2

#(lambda x : x+2) # 1줄 함수 
df

ValueError: Cannot specify ',' with 's'.

In [29]:
def cal(x):
    return x+2

#(lambda x : x+2) # 1줄 함수 
df

          영화  개봉 연도   관객 수    평점
0         명량   2014  1,761  8.88
1       극한직업   2019  1,626  9.20
2  신과함께-죄와 벌   2017  1,441  8.73
3       국제시장   2014  1,426  9.16
4         괴물   2006  1,301  8.62
5        도둑들   2012  1,298  7.64
6    7번방의 선물   2013  1,281  8.83
7         암살   2015  1,270  9.10

In [60]:
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}
df = pd.DataFrame(data)
# df.set_index('영화', inplace=True) 
df

          영화  개봉 연도  관객 수    평점
0         명량   2014  1761  8.88
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
3       국제시장   2014  1426  9.16
4         괴물   2006  1301  8.62
5        도둑들   2012  1298  7.64
6    7번방의 선물   2013  1281  8.83
7         암살   2015  1270  9.10

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   영화      8 non-null      str
 1   개봉 연도   8 non-null      int64
 2   관객 수    8 non-null      int64
 3   평점      8 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 388.0 bytes

In [ ]:
#  개봉연도 내림차순, 오름차순 으로 출력하시오.
# df.info()
df.sort_values('개봉 연도')
df['개봉 연도'].sort_values(ascending=True)
df['개봉 연도'].sort_values(ascending=False)
df

          영화  개봉 연도  관객 수    평점
0         명량   2014  1761  8.88
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
3       국제시장   2014  1426  9.16
4         괴물   2006  1301  8.62
5        도둑들   2012  1298  7.64
6    7번방의 선물   2013  1281  8.83
7         암살   2015  1270  9.10

In [63]:
#  평점이 9점이상만 출력하시오.
flit = df['평점']>=9
df[flit]

     영화  개봉 연도  관객 수    평점
1  극한직업   2019  1626  9.20
3  국제시장   2014  1426  9.16
7    암살   2015  1270  9.10

In [66]:
#  평점 컬럼 내용에 8.88점 글자를 넣어서 출력하시오.
df['평점'] = df['평점'].astype(str)+'점'
df

          영화  개봉 연도  관객 수     평점
0         명량   2014  1761  8.88점
1       극한직업   2019  1626   9.2점
2  신과함께-죄와 벌   2017  1441  8.73점
3       국제시장   2014  1426  9.16점
4         괴물   2006  1301  8.62점
5        도둑들   2012  1298  7.64점
6    7번방의 선물   2013  1281  8.83점
7         암살   2015  1270   9.1점

In [64]:
# 평점중에 평점 평균이상인 row만 출력하시오.
flit = df['평점'] >= df['평점'].mean()
df[flit]

        영화  개봉 연도  관객 수    평점
0       명량   2014  1761  8.88
1     극한직업   2019  1626  9.20
3     국제시장   2014  1426  9.16
6  7번방의 선물   2013  1281  8.83
7       암살   2015  1270  9.10

In [67]:
# 2015년 이후에 개봉한 영화를 출력하시오.
flit = df['개봉 연도'] >= 2015
df[flit]

          영화  개봉 연도  관객 수     평점
1       극한직업   2019  1626   9.2점
2  신과함께-죄와 벌   2017  1441  8.73점
7         암살   2015  1270   9.1점