In [12]:
import pandas as pd

In [ ]:
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}

          영화  개봉 연도  관객 수    평점
0         명량   2014  1761  8.88
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
3       국제시장   2014  1426  9.16
4         괴물   2006  1301  8.62
5        도둑들   2012  1298  7.64
6    7번방의 선물   2013  1281  8.83
7         암살   2015  1270  9.10

In [ ]:
# 최대값 관객수 출력
# 전체 관객수 평균을 출력
# 평점 상위 3개를 출력하시오.
# 평점 하위 5개를 출력하시오.
# 영화를 index로 역순정렬하시오.
# screen.xlsx파일로 저장하시오.

df.to_excel('file/movie.xlsx')

             영화  개봉 연도    평점
관객 수
1761         명량   2014  8.88
1626       극한직업   2019  9.20
1441  신과함께-죄와 벌   2017  8.73
1426       국제시장   2014  9.16
1301         괴물   2006  8.62
1298        도둑들   2012  7.64
1281    7번방의 선물   2013  8.83
1270         암살   2015  9.10

In [ ]:
# 최대값 관객수 출력

df = pd.read_excel('file/movie.xlsx',usecols='A') 
df

   관객 수
0  1761
1  1626
2  1441
3  1426
4  1301
5  1298
6  1281
7  1270

In [ ]:
# 전체 관객수 평균을 출력

df = pd.read_excel('file/movie.xlsx')
df['관객 수'].mean()

np.float64(1425.5)

In [11]:
# 평점 상위 3개를 출력하시오.
df = pd.read_excel('file/movie.xlsx')

df.index = df.index + 1
df.head(3)

   관객 수         영화  개봉 연도    평점
1  1761         명량   2014  8.88
2  1626       극한직업   2019  9.20
3  1441  신과함께-죄와 벌   2017  8.73

In [15]:
# 평점 하위 5개를 출력하시오.
df = pd.read_excel('file/movie.xlsx')
df = df[3:]
df.index = range(1, len(df) + 1)
df.tail(5)

   관객 수       영화  개봉 연도    평점
1  1426     국제시장   2014  9.16
2  1301       괴물   2006  8.62
3  1298      도둑들   2012  7.64
4  1281  7번방의 선물   2013  8.83
5  1270       암살   2015  9.10

In [23]:
# 영화를 index로 역순정렬하시오.
df = pd.read_excel('file/movie.xlsx')
df.sort_index(ascending=False, inplace=True)
df

   관객 수         영화  개봉 연도    평점
7  1270         암살   2015  9.10
6  1281    7번방의 선물   2013  8.83
5  1298        도둑들   2012  7.64
4  1301         괴물   2006  8.62
3  1426       국제시장   2014  9.16
2  1441  신과함께-죄와 벌   2017  8.73
1  1626       극한직업   2019  9.20
0  1761         명량   2014  8.88

In [41]:
df = pd.read_excel('file/movie.xlsx')
df['평점'].nsmallest(5)

5    7.64
4    8.62
2    8.73
6    8.83
0    8.88
Name: 평점, dtype: float64

In [42]:
df = pd.read_excel('file/movie.xlsx')
df['평점'].nlargest(3)

1    9.20
3    9.16
7    9.10
Name: 평점, dtype: float64