In [3]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False 
matplotlib.rcParams['font.family'] = 'Malgun Gothic' 
matplotlib.rcParams['font.size'] 
import pandas as pd
import numpy as np

In [4]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import requests
from bs4 import BeautifulSoup
import time
import os
from dotenv import load_dotenv

In [11]:
df=pd.read_csv('file/namu1-2.csv')
df

,Unnamed: 0,title,url
0,0,더미 플러그,https://namu.wiki/w/%EB%8D%94%EB%AF%B8%20%ED%9...
1,1,하치미야 메구루,https://namu.wiki/w/%ED%95%98%EC%B9%98%EB%AF%B...
2,2,히트펌프,https://namu.wiki/w/%ED%9E%88%ED%8A%B8%ED%8E%8...
3,3,주노(오버워치),https://namu.wiki/w/%EC%A3%BC%EB%85%B8(%EC%98%...
4,4,황성빈/통산 도루 일지,https://namu.wiki/w/%ED%99%A9%EC%84%B1%EB%B9%8...
...,...,...,...
95,95,명군이 되어보세!/등장인물/4부,https://namu.wiki/w/%EB%AA%85%EA%B5%B0%EC%9D%B...
96,96,아구스틴 기아이,https://namu.wiki/w/%EC%95%84%EA%B5%AC%EC%8A%A...
97,97,메르시,https://namu.wiki/w/%EB%A9%94%EB%A5%B4%EC%8B%9C
98,98,노움(워크래프트 시리즈),https://namu.wiki/w/%EB%85%B8%EC%9B%80(%EC%9B%...
99,99,굿모닝! 티처,https://namu.wiki/w/%EA%B5%BF%EB%AA%A8%EB%8B%9...

In [12]:
data_1 = []
for url in df['url'].head(50):
    print(url)

https://namu.wiki/w/%EB%8D%94%EB%AF%B8%20%ED%94%8C%EB%9F%AC%EA%B7%B8
https://namu.wiki/w/%ED%95%98%EC%B9%98%EB%AF%B8%EC%95%BC%20%EB%A9%94%EA%B5%AC%EB%A3%A8
https://namu.wiki/w/%ED%9E%88%ED%8A%B8%ED%8E%8C%ED%94%84
https://namu.wiki/w/%EC%A3%BC%EB%85%B8(%EC%98%A4%EB%B2%84%EC%9B%8C%EC%B9%98)
https://namu.wiki/w/%ED%99%A9%EC%84%B1%EB%B9%88/%ED%86%B5%EC%82%B0%20%EB%8F%84%EB%A3%A8%20%EC%9D%BC%EC%A7%80
https://namu.wiki/w/%EC%95%84%EB%A6%AC%EC%8A%A4%20%EB%A7%88%EB%A6%AC%EC%95%84
https://namu.wiki/w/%EB%86%80%EB%A1%9C
https://namu.wiki/w/%EC%84%9C%EC%9A%B8%EB%82%A8%EB%B6%80%ED%84%B0%EB%AF%B8%EB%84%90/%EC%9A%B4%ED%96%89%EB%85%B8%EC%84%A0
https://namu.wiki/w/%EC%A4%80%EB%B8%8C%EB%A0%88%EB%93%9C
https://namu.wiki/w/%EB%B6%84%EB%A5%98:MSG%EC%95%BC%EA%B5%AC%EB%8B%A8%20%EC%B6%9C%EC%8B%A0
https://namu.wiki/w/%EA%B3%A0%EB%A6%AC%EC%9D%98%20%EB%8F%84%EC%8B%9C
https://namu.wiki/w/%ED%8C%8C%EB%94%94%EC%95%84
https://namu.wiki/w/%EC%82%AC%EC%BF%A0%EB%9D%BC%EA%B8%B0%20%EB%A7%88%EB%85%B8
https://namu.wiki/w/%ED%9E%88%ED%8A%B8%ED%8E%8C%ED%94%84
https://namu.wiki/w/1924%EB%85%84
https://namu.wiki/w/%EC%A7%84%EC%84%9D%EB%B2%94
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:Nolo_2026_path-9.png
https://namu.wiki/w/%EC%84%9C%EC%9A%B8%EB%82%A8%EB%B6%80%ED%84%B0%EB%AF%B8%EB%84%90/%EC%9A%B4%ED%96%89%EB%85%B8%EC%84%A0
https://namu.wiki/w/TBC%20%EB%9D%BC%EC%A7%80%EC%98%A4
https://namu.wiki/w/%ED%86%A0%EB%A7%88%EC%8B%9C%20%EC%88%98%EC%8A%AC%EB%A1%9C%ED%94%84
https://namu.wiki/w/RESCENE/%EA%B3%B5%EC%97%B0%20%EB%B0%8F%20%ED%96%89%EC%82%AC
https://namu.wiki/w/%EB%B2%A0%EC%9D%B4%EC%8A%A4%20%EB%AE%A4%EC%A7%81
https://namu.wiki/w/%ED%81%AC%EB%A1%9C%EC%8A%A4%20%EA%B8%B8%EB%93%9C
https://namu.wiki/w/%EB%8F%84%EB%9D%BC%EC%97%90%EB%AA%BD/%EC%8B%9C%EA%B0%84%EB%8C%80
https://namu.wiki/w/%EC%9D%B4%EC%83%81%20%EA%B3%A0%EC%98%A8/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD/21%EC%84%B8%EA%B8%B0/2020%EB%85%84%EB%8C%80
https://namu.wiki/w/%EC%95%84%EB%A6%AC%EC%8A%A4%EA%B0%80%EC%99%80%20%EB%82%98%EC%B8%A0%ED%95%98
https://namu.wiki/w/%EB%B9%84%ED%96%89(%EB%9E%98%ED%8D%BC)
https://namu.wiki/w/%EB%8D%94%EB%AF%B8%20%ED%94%8C%EB%9F%AC%EA%B7%B8
https://namu.wiki/w/2XKO
https://namu.wiki/w/%EC%95%84%EB%8B%B4%20%EC%98%A4%EB%B2%A0%EB%A5%B4%ED%8A%B8
https://namu.wiki/w/%EB%B2%A0%EC%9D%B4%EC%8A%A4%20%EB%AE%A4%EC%A7%81
https://namu.wiki/w/%EC%97%90%EB%B0%94%20%EB%A7%88%EB%A6%AC%20%EC%84%B8%EC%9D%B8%ED%8A%B8
https://namu.wiki/w/%EC%9D%B4%EC%A7%84%EC%88%98(1976)
https://namu.wiki/w/%EC%A3%BC%EB%85%B8(%EC%98%A4%EB%B2%84%EC%9B%8C%EC%B9%98)
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:%EC%98%A4%EB%B2%84%EC%9B%8C%EC%B9%98%20%EC%9A%B0%EC%96%91%20%EC%8B%A0%ED%99%94%20%EC%9A%A9%EC%9D%98%20%ED%98%91%EA%B0%9D.png
https://namu.wiki/w/%EC%95%84%EB%A6%AC%EC%8A%A4%EA%B0%80%EC%99%80%20%EB%82%98%EC%B8%A0%ED%95%98
https://namu.wiki/w/2026%20%EC%95%84%EC%9D%B4%EC%B9%98%C2%B7%EB%82%98%EA%B3%A0%EC%95%BC%20%EC%95%84%EC%8B%9C%EC%95%88%20%EA%B2%8C%EC%9E%84%20%EA%B5%B0%EB%A9%B4%EC%A0%9C%20%EB%B0%9C%EC%96%B8%20%EB%85%BC%EB%9E%80
https://namu.wiki/w/%EB%A6%AC%EC%98%A4%EB%84%AC%20%EB%A9%94%EC%8B%9C/%EA%B5%AD%EA%B0%80%EB%8C%80%ED%91%9C%20%EA%B2%BD%EB%A0%A5/2026%20FIFA%20%EC%9B%94%EB%93%9C%EC%BB%B5
https://namu.wiki/w/%EC%82%AC%EC%9A%A9%EC%9E%90:tmfjfkdskr
https://namu.wiki/w/TBC%20%EB%9D%BC%EB%94%94%EC%98%A4
https://namu.wiki/w/%EB%AA%A8%EB%AA%A8%EC%B9%B4%ED%92%80
https://namu.wiki/w/2026%20%EB%82%B4%EC%85%94%EB%84%90%20%EB%A6%AC%EA%B7%B8%20%EB%94%94%EB%B9%84%EC%A0%84%20%EC%8B%9C%EB%A6%AC%EC%A6%88
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:%EC%98%A4%EB%B2%84%EC%9B%8C%EC%B9%98%20%EB%A3%A8%EC%8B%9C%EC%9A%B0%20%EC%8B%A0%ED%99%94%20%EB%AC%B4%EA%B8%B0%20%ED%8A%B8%EB%A0%88%EB%B8%94%EB%A9%94%EC%9D%B4%EC%BB%A4.png
https://namu.wiki/w/2026%EB%85%84
https://namu.wiki/w/%EC%A1%B0%EC%84%9C%EC%97%B0(%EC%95%84%EB%82%98%EC%9A%B4%EC%84%9C)
https://namu.wiki/w/%EC%A1%B0%EB%8D%98%20%ED%98%B8%ED%82%A8%EC%8A%A4
https://namu.wiki/w/9%EA%B8%89%20%EA%B3%B5%EB%AC%B4%EC%9B%90
https://namu.wiki/w/%EC%B0%BD%EC%9B%90%20%EB%B2%84%EC%8A%A4%20213
https://namu.wiki/w/%EA%B0%95%ED%95%B4%EB%9D%BC(%EC%9A%95%EB%A7%9D%EC%9D%98%20%EB%8D%AB)
https://namu.wiki/w/X%20JAPAN

In [13]:
url = 'https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:SHIDA4.gif'
res = requests.get(url)
soup = BeautifulSoup(res.text,'lxml')

# None 체크 추가
title_tag = soup.find('h1')
category_tag = soup.find('ul')
content_tag = soup.find('div')

title = title_tag.get_text(strip=True) if title_tag else 'N/A'
category = category_tag.get_text(strip=True) if category_tag else 'N/A'
content = content_tag.get_text(strip=True) if content_tag else 'N/A'

print(f"title: {title}")
print(f"category: {category}")
print(f"content: {content[:100]}")

title: N/A
category: N/A
content: Loading...

In [15]:
data = []
for url in df['url'].head(50):
    res = requests.get(url)
    time.sleep(1)
    soup = BeautifulSoup(res.text,'lxml') 
    title_tag = soup.find('a',{'class':'J23-5aq4'})

    title_node = soup.find('h1', {'class': 'iVt87Y2e'})
    title = title_node.get_text(strip=True) if title_node else '제목 없음'

    category_node = soup.find('div', {'class': 'pwd1cbSV'})
    category = category_node.get_text(strip=True) if category_node else '카테고리 없음'

    content_node = soup.find('div', {'class': '_8S+cJoAM'})
    content = content_node.get_text(strip=True) if content_node else '본문 없음'
    data.append({
        'title':title,
        'category':category,
        'content':content
    })
    print(title)

print('완료')

더미 플러그
하치미야 메구루
히트펌프
주노(오버워치)
황성빈/통산 도루 일지
아리스 마리아
놀로
서울남부터미널/운행노선
준브레드
분류:MSG야구단 출신
고리의 도시
파디아
사쿠라기 마노
히트펌프
1924년
진석범
제목 없음
서울남부터미널/운행노선
도호쿠 방송
토마시 수슬로프
RESCENE/공연 및 행사
베이스 뮤직
크로스 길드
도라에몽/시간대
이상 고온/대한민국/21세기/2020년대
아리스가와 나츠하
비행(래퍼)
더미 플러그
2XKO
아담 오베르트
베이스 뮤직
에바 마리 세인트
이진수(1976)
주노(오버워치)
제목 없음
아리스가와 나츠하
2026 아이치·나고야 아시안 게임 군면제 발언 논란
리오넬 메시/국가대표 경력/2026 FIFA 월드컵
사용자:tmfjfkdskr
도호쿠 방송
모모카풀
2026 내셔널 리그 디비전 시리즈
제목 없음
2026년
조서연(아나운서)
조던 호킨스
9급 공무원
창원 버스 213
강해라(욕망의 덫)
X JAPAN
완료

In [16]:
df=pd.read_csv('file/namu1-2.csv')
df

,Unnamed: 0,title,url
0,0,더미 플러그,https://namu.wiki/w/%EB%8D%94%EB%AF%B8%20%ED%9...
1,1,하치미야 메구루,https://namu.wiki/w/%ED%95%98%EC%B9%98%EB%AF%B...
2,2,히트펌프,https://namu.wiki/w/%ED%9E%88%ED%8A%B8%ED%8E%8...
3,3,주노(오버워치),https://namu.wiki/w/%EC%A3%BC%EB%85%B8(%EC%98%...
4,4,황성빈/통산 도루 일지,https://namu.wiki/w/%ED%99%A9%EC%84%B1%EB%B9%8...
...,...,...,...
95,95,명군이 되어보세!/등장인물/4부,https://namu.wiki/w/%EB%AA%85%EA%B5%B0%EC%9D%B...
96,96,아구스틴 기아이,https://namu.wiki/w/%EC%95%84%EA%B5%AC%EC%8A%A...
97,97,메르시,https://namu.wiki/w/%EB%A9%94%EB%A5%B4%EC%8B%9C
98,98,노움(워크래프트 시리즈),https://namu.wiki/w/%EB%85%B8%EC%9B%80(%EC%9B%...
99,99,굿모닝! 티처,https://namu.wiki/w/%EA%B5%BF%EB%AA%A8%EB%8B%9...

In [ ]:
# df['url']

for url in df['url']:
    print(url)

https://namu.wiki/w/%EC%A1%B0%EC%A7%80%20%EC%9B%A8%EC%95%84
https://namu.wiki/w/%EA%B2%BD%EC%A7%80
https://namu.wiki/w/%EA%B5%B0%EC%82%B0%20%EB%B2%84%EC%8A%A4%2019
https://namu.wiki/w/House%202
https://namu.wiki/w/%EC%9E%A5%EA%B0%91%EA%B8%B0%EB%B3%91%20%EB%B3%B4%ED%86%B0%EC%A6%88%20%ED%9A%8C%EC%83%89%EC%9D%98%20%EB%A7%88%EB%85%80
https://namu.wiki/w/%EC%B9%B4%EB%93%9C%20%EC%95%99%20%EC%8B%9C%EC%97%98/%EC%B9%B4%EB%93%9C/%EB%93%9C%EB%A1%9C
https://namu.wiki/w/%EC%82%AC%EC%9A%A9%EC%9E%90:SamSara
https://namu.wiki/w/%EC%95%8C%ED%84%B0(%EC%9B%8C%ED%81%AC%EB%9E%98%ED%94%84%ED%8A%B8%203)
https://namu.wiki/w/%EB%B9%85%20%EB%AF%B8%ED%82%A4
https://namu.wiki/w/%EC%A0%9C%EC%9E%84%EC%8A%A4%20%EB%A1%9C%EB%8B%88
https://namu.wiki/w/%EC%A0%9C25%EB%B3%B4%EB%B3%91%EC%82%AC%EB%8B%A8%20DMZ%20%EC%A7%80%EB%A2%B0%20%ED%8F%AD%EB%B0%9C%20%EC%82%AC%EA%B1%B4
https://namu.wiki/w/%ED%83%B1%ED%82%B9
https://namu.wiki/w/%EC%99%80%EB%8B%A4
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:NSL-Hip-Hop-2.jpg
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:%EA%B9%80%EB%8C%80%ED%98%84(1995)_%ED%94%84%EB%A1%9C%ED%95%84%EC%82%AC%EC%A7%84.jpg
https://namu.wiki/w/%EB%AA%85%ED%83%90%EC%A0%95%20%EC%BD%94%EB%82%9C:%20%EC%8B%9C%ED%95%9C%EC%9E%A5%EC%B9%98%EC%9D%98%20%EB%A7%88%EC%B2%9C%EB%A3%A8
https://namu.wiki/w/%EC%95%8C%ED%83%80(%EC%9B%8C%ED%81%AC%EB%9E%98%ED%94%84%ED%8A%B8%203)
https://namu.wiki/w/%EC%98%81%EC%B2%9C%EC%8B%9C/%EC%A0%95%EC%B9%98
https://namu.wiki/w/%EA%B7%B9%EC%9E%A5%ED%8C%90%20%EC%9D%B4%EB%82%98%EC%A6%88%EB%A7%88%20%EC%9D%BC%EB%A0%88%EB%B8%90%20%EC%B5%9C%EA%B0%95%EA%B5%B0%EB%8B%A8%20%EC%98%A4%EC%9A%B0%EA%B1%B0%EC%9D%98%20%EC%8A%B5%EA%B2%A9
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:%EA%B5%B0%EC%82%B0%20%EB%B2%84%EC%8A%A4%2019%EB%B2%88%20%EC%9A%B0%EC%84%B1%EC%97%AC%EA%B0%9D%202023%ED%98%B8.jpg
https://namu.wiki/w/1991%EB%85%84%20%EC%9D%B4%EB%9D%BC%ED%81%AC%20%EB%B4%89%EA%B8%B0
https://namu.wiki/w/2003%20%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%9C%A0%EB%9F%BD%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C
https://namu.wiki/w/%EB%B6%88%EA%BD%83%20%ED%8C%8C%EC%9D%B4%ED%84%B0%EC%A6%88/%EC%97%AD%EB%8C%80%20%EC%A0%84%EC%A0%81/2026%20%EC%8B%9C%EC%A6%8C/%EA%B2%BD%EA%B8%B0%20%EB%AA%A9%EB%A1%9D
https://namu.wiki/w/%ED%9D%91%EC%83%89%EC%99%9C%EC%84%B1
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:%ED%8F%AC%EC%8A%A4%ED%84%B0%206888%20%EC%A4%91%EC%95%99%EC%9A%B0%ED%8E%B8%EB%8C%80%EB%8C%80.jpg
https://namu.wiki/w/%EA%B9%80%ED%99%98%ED%9D%AC/%EA%B3%A8%20%EB%95%8C%EB%A6%AC%EB%8A%94%20%EA%B7%B8%EB%85%80%EB%93%A4/%ED%81%B4%EB%9F%BD%20%EA%B2%BD%EB%A0%A5
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:NS01.jpg
https://namu.wiki/w/%EC%82%AC%EC%9A%A9%EC%9E%90:Hexy_Joe/%EB%B9%A0%EB%A5%B8%20%EC%9D%B4%EB%8F%99%20%EB%B0%8F%20%EC%97%B0%EC%8A%B5%EC%9E%A5
https://namu.wiki/w/%EB%82%9C%EC%B9%B8%EB%A7%88%EC%B9%98
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:%EB%82%9C%EC%B9%B8%EB%A7%88%EC%B9%98%20%EB%A1%9C%EA%B3%A0.png
https://namu.wiki/w/%EC%86%90%EB%AC%B4
https://namu.wiki/w/FSO%20%ED%8F%B4%EB%A1%9C%EB%84%A4%EC%A6%88
https://namu.wiki/w/2002%20%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%9C%A0%EB%9F%BD%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C
https://namu.wiki/w/PC%EC%A0%95%EB%B9%84%EC%82%AC
https://namu.wiki/w/%EB%B6%88%EA%BD%83%20%ED%8C%8C%EC%9D%B4%ED%84%B0%EC%A6%88/%EC%97%AD%EB%8C%80%20%EC%A0%84%EC%A0%81/2026%20%EC%8B%9C%EC%A6%8C/%EA%B2%BD%EA%B8%B0%20%EB%AA%A9%EB%A1%9D
https://namu.wiki/w/%EB%B6%84%EB%A5%98:%EB%B0%94%ED%8A%B8%EC%A3%BC%EC%9D%98%20%EC%9D%B4%EB%9D%BC%ED%81%AC%EC%9D%98%20%EC%A0%84%EC%9F%81%20%EB%B0%8F%20%EC%A0%84%ED%88%AC
https://namu.wiki/w/%EA%B9%80%ED%99%98%ED%9D%AC/%EA%B3%A8%20%EB%95%8C%EB%A6%AC%EB%8A%94%20%EA%B7%B8%EB%85%80%EB%93%A4/%ED%81%B4%EB%9F%BD%20%EA%B2%BD%EB%A0%A5/FC%20%EC%95%A1%EC%85%94%EB%8B%88%EC%8A%A4%ED%83%80
https://namu.wiki/w/%EC%95%88%EC%96%91%20%EC%A0%95%EA%B4%80%EC%9E%A5%20%EB%A0%88%EB%93%9C%EB%B6%80%EC%8A%A4%ED%84%B0%EC%8A%A4
https://namu.wiki/w/%EC%9E%94%EC%8A%A4%ED%8C%8C%EC%9D%B8/SD%EA%B1%B4%EB%8B%B4%20%EC%A7%80%20%EC%A0%9C%EB%84%A4%EB%A0%88%EC%9D%B4%EC%85%98%20%EC%9D%B4%ED%84%B0%EB%84%90/UR
https://namu.wiki/w/%EC%82%AC%EC%9A%A9%EC%9E%90:SamSara
https://namu.wiki/w/%EB%B6%80%EC%82%B0%20OK%EC%A0%80%EC%B6%95%EC%9D%80%ED%96%89%20%EC%9D%8F%EB%A7%A8
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:%EB%B1%80%ED%94%84%ED%82%B9%20%EB%8F%84%EB%8F%84.png
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:%EB%82%9C%EC%B9%B8%EB%A7%88%EC%B9%98%20%EB%A1%9C%EA%B3%A0.png
https://namu.wiki/w/%ED%86%A0%EC%98%A4%EC%82%AC%EC%B9%B4%20%EB%A6%B0/%EC%9E%91%EC%A4%91%20%ED%96%89%EC%A0%81/%EB%B3%B8%ED%8E%B8
https://namu.wiki/w/%EA%B9%80%EC%A3%BC%EC%84%B1(%EC%95%BC%EA%B5%AC%EC%84%A0%EC%88%98)/%EC%84%A0%EC%88%98%20%EA%B2%BD%EB%A0%A5
https://namu.wiki/w/%EB%A6%AC%EA%B7%B8%20%EC%98%A4%EB%B8%8C%20%EB%A0%88%EC%A0%84%EB%93%9C/%EC%A6%9D%EA%B0%95/%ED%94%84%EB%A6%AC%EC%A6%98
https://namu.wiki/w/%EC%A1%B0%EC%A7%80%20%EC%9B%A8%EC%95%84
https://namu.wiki/w/%EC%82%AC%EC%9A%A9%EC%9E%90:Wpdl
https://namu.wiki/w/%EC%95%84%EC%8A%A4%ED%8C%8C%EB%A5%B4
https://namu.wiki/w/2025%EB%85%84/%EC%82%AC%EA%B1%B4
https://namu.wiki/w/%EC%99%80%EB%8B%A4
https://namu.wiki/w/%EA%B9%80%EC%8A%B9%ED%98%9C
https://namu.wiki/w/%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%9C%A0%EB%9F%BD%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C
https://namu.wiki/w/%EC%B9%B4%EB%93%9C%20%EC%95%99%20%EC%8B%9C%EC%97%98/%EC%B9%B4%EB%93%9C/%EB%93%9C%EB%A1%9C
https://namu.wiki/w/%EC%A1%B0%EC%98%81%EC%9A%B0(2004)
https://namu.wiki/w/%EB%82%A8%EA%B6%81%EC%9D%B8
https://namu.wiki/w/SNH48%20%EA%B7%B8%EB%A3%B9
https://namu.wiki/w/%EB%8D%94%EB%A6%AC%EB%B8%8C
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:%EB%B1%80%ED%94%84%ED%82%B9%20%EB%8F%84%EB%8F%84.png
https://namu.wiki/w/%EC%A0%9C%EB%8B%A8(%EC%9B%8C%ED%81%AC%EB%9E%98%ED%94%84%ED%8A%B8%203)
https://namu.wiki/w/%EB%A0%88%EC%98%A4%201%EC%84%B8
https://namu.wiki/w/%EB%8D%94%EB%A6%AC%EB%B8%8C
https://namu.wiki/w/%ED%99%A9%EC%9C%A0%EB%AF%BC
https://namu.wiki/w/%ED%8B%80:%EB%83%89%EC%A0%84/%EB%AF%B8%EA%B5%AD%20%EB%B3%B4%EB%B3%91%EC%9E%A5%EB%B9%84
https://namu.wiki/w/%ED%8B%80:%EB%83%89%EC%A0%84/%EB%AF%B8%EA%B5%AD%20%EB%B3%B4%EB%B3%91%EC%9E%A5%EB%B9%84
https://namu.wiki/w/%EB%9D%BC%EC%9D%B8%EB%A7%A8
https://namu.wiki/w/%EC%A0%9C%EB%8B%A8(%EC%9B%8C%ED%81%AC%EB%9E%98%ED%94%84%ED%8A%B8%203)
https://namu.wiki/w/%EC%BF%A0%ED%82%A4%EB%9F%B0/%EB%B3%B4%EB%AC%BC/%EB%B3%B4%EB%AC%BC%EB%BD%91%EA%B8%B0/S%EA%B8%89/%EC%B2%B4%EB%A0%A5%EB%B3%B4%EC%A0%95%EB%B0%8F%20%EC%9D%B4%EB%8F%99%EC%86%8D%EB%8F%84%20%EC%A0%9C%EC%99%B8%20%EB%B3%B4%EB%AC%BC
https://namu.wiki/w/%ED%95%A8%EC%B0%BD%EC%A4%91%EC%95%99%EC%B4%88%EB%93%B1%ED%95%99%EA%B5%90
https://namu.wiki/w/%EB%B6%80%EC%82%B0%20OK%EC%A0%80%EC%B6%95%EC%9D%80%ED%96%89%20%EC%9D%8F%EB%A7%A8
https://namu.wiki/w/1%20%EB%8C%80%20100/%EB%B0%A9%EC%98%81%20%EB%AA%A9%EB%A1%9D/2016~2018%EB%85%84
https://namu.wiki/w/%ED%8F%AC%EB%A5%B4%EC%9E%90%20%ED%98%B8%EB%9D%BC%EC%9D%B4%EC%A6%8C%206/%ED%8F%89%EA%B0%80
https://namu.wiki/w/%EC%A1%B0%EC%A7%80%20%EC%9B%A8%EC%95%84
https://namu.wiki/w/%EC%95%94%EC%82%B4%EC%9E%90(%EB%93%A4)/%EB%93%B1%EC%9E%A5%EC%9D%B8%EB%AC%BC
https://namu.wiki/w/%ED%8B%80:%ED%99%A9%EB%AF%BC%ED%98%84
https://namu.wiki/w/%EC%8B%9D%EC%8A%A4%20%ED%94%8C%EB%9E%98%EA%B7%B8%20%ED%82%A4%EB%94%94%EC%95%BC%20%EC%8B%9C%ED%8B%B0
https://namu.wiki/w/%ED%9B%84%EC%A7%80%EC%B9%B4%EC%99%80%20%ED%81%90%EC%A7%80
https://namu.wiki/w/%EB%B6%81%ED%95%AD%EC%B9%9C%EC%88%98%EA%B3%B5%EC%9B%90%20%EC%83%81%EC%96%B4%20%EC%B6%9C%EB%AA%B0%20%EC%82%AC%EA%B1%B4
https://namu.wiki/w/%EB%95%8C%EB%A6%AC%EB%A9%8D
https://namu.wiki/w/%EB%B6%80%EC%BA%89%EC%9D%B4
https://namu.wiki/w/%ED%8B%80:%EC%97%AD%EB%8C%80%20%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%9C%A0%EB%9F%BD%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C%20%EB%82%A8%EC%9E%90%EB%B6%80%20%EC%A2%85%ED%95%A9%20%EC%88%9C%EC%9C%84
https://namu.wiki/w/%EA%B9%80%ED%99%98%ED%9D%AC/%EA%B3%A8%20%EB%95%8C%EB%A6%AC%EB%8A%94%20%EA%B7%B8%EB%85%80%EB%93%A4/%EC%8B%9C%EC%A6%8C%209
https://namu.wiki/w/%EC%A0%9C%EB%8B%A8(%EC%9B%8C%ED%81%AC%EB%9E%98%ED%94%84%ED%8A%B8%203)
https://namu.wiki/w/%EB%8D%B0%EC%A7%80%EB%A0%88%20%EB%91%90%EC%97%90
https://namu.wiki/w/%EC%A1%B0%ED%9D%AC%EB%8C%80/%EB%85%BC%EB%9E%80%20%EB%B0%8F%20%EC%82%AC%EA%B1%B4%20%EC%82%AC%EA%B3%A0
https://namu.wiki/w/%ED%86%B5%ED%96%89%EB%B0%A9%ED%96%A5/%EC%B0%A8%EB%A7%88
https://namu.wiki/w/%EB%B6%88%EA%BD%83%20%ED%8C%8C%EC%9D%B4%ED%84%B0%EC%A6%88/%EC%97%AD%EB%8C%80%20%EC%A0%84%EC%A0%81/2026%20%EC%8B%9C%EC%A6%8C/%EA%B2%BD%EA%B8%B0%20%EB%AA%A9%EB%A1%9D
https://namu.wiki/w/%ED%8B%80:%ED%95%B4%EB%82%98(%EC%97%94%EC%A0%A4%EB%85%B8%EC%9D%B4%EC%A6%88)
https://namu.wiki/w/%EC%A1%B0%ED%9D%AC%EB%8C%80/%EC%83%9D%EC%95%A0
https://namu.wiki/w/%EC%A1%B0%EC%A7%80%20%EC%9B%A8%EC%95%84
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:pvzs39.png
https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:%EB%82%98%EA%B3%A0%EB%AF%B8%EB%A7%88%EC%B9%98%20%EB%AC%B8%EC%9E%A5.svg
https://namu.wiki/w/%EB%BB%98%EB%AF%B8%EC%8A%A4
https://namu.wiki/w/%EB%AC%B4%EB%84%88%EC%A7%84%20%EC%84%B1%EC%9E%90%20%EB%AF%B8%EC%B9%B4%EC%97%98%EB%9D%BC%20%EB%A0%88%EC%9D%B4%EB%93%9C/%EB%8D%98%EC%A0%84/1%2C%202%ED%8E%98%EC%9D%B4%EC%A6%88
https://namu.wiki/w/%ED%92%8B%EB%B3%BC%EB%A7%A4%EB%8B%88%EC%A0%80/%EC%84%A0%EC%88%98%20%EB%8A%A5%EB%A0%A5%EC%B9%98
https://namu.wiki/w/%EB%85%B8%ED%83%9C%EC%95%85%20%EB%8C%80%EB%B2%95%EA%B4%80%20%ED%9B%84%EC%9E%84%20%EC%9D%B8%EC%84%A0%20%EA%B0%88%EB%93%B1%20%EC%82%AC%ED%83%9C
https://namu.wiki/w/%ED%8B%80:%EC%97%AD%EB%8C%80%20%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%9C%A0%EB%9F%BD%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C%20%EC%97%AC%EC%9E%90%EB%B6%80%20%EC%9A%B0%EC%8A%B9%EC%9E%90
https://namu.wiki/w/%EC%82%AC%EC%9A%A9%EC%9E%90:cookingdumo0o/%EC%97%B0%EC%8A%B5%EC%9E%A5
https://namu.wiki/w/%EC%B9%B4%EB%A9%94%EC%A7%90
https://namu.wiki/w/%ED%8B%80:%EC%97%AD%EB%8C%80%20%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99%20%EC%8A%A4%ED%94%BC%EB%93%9C%20%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8C%85%20%EC%9C%A0%EB%9F%BD%EC%84%A0%EC%88%98%EA%B6%8C%20%EB%8C%80%ED%9A%8C%20%EC%97%AC%EC%9E%90%EB%B6%80%20%EC%A2%85%ED%95%A9%20%EC%88%9C%EC%9C%84

In [1]:
# url = 'https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:SHIDA4.gif'
# res = requests.get(url)
# soup = BeautifulSoup(res.text,'lxml')
# title = soup.find('a',{'class':'J23-5aq4'}).get_text(strip=True)
# category = soup.find('ul',{'class':'EVpyuXop'}).get_text(strip=True)
# content = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'}).get_text(strip=True)

In [ ]:
data = []
for url in df['url'].head(50):
    # # 2. selenium : 자동화 도구 - 스크롤없이 가져옴
    # namu_url = url
    # options = Options()
    # options.add_experimental_option("excludeSwitches", ["enable-automation"])
    # options.add_experimental_option("useAutomationExtension", False)
    # options.add_argument("--disable-blink-features=AutomationControlled")
    # browser = webdriver.Chrome(options=options)
    # browser.maximize_window() # 화면 최대창 확대
    # browser.get(namu_url)
    # time.sleep(2)
    res = requests.get(url)
    time.sleep(1)
    soup = BeautifulSoup(res.text,'lxml') 
    title_tag = soup.find('a',{'class':'J23-5aq4'})
    title = title_tag.get_text(strip=True) if title_tag else None
    category_tag = soup.find('ul',{'class':'EVpyuXop'})
    category = category_tag.get_text(strip=True) if category_tag else None
    content_tag = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'})
    content = content_tag.get_text(strip=True) if content_tag else None
    data.append({
        'title':title,
        'category':category,
        'content':content
    })
    print(title)

print('완료')

In [5]:
url = 'https://namu.wiki/w/%EC%A1%B0%EC%A7%80%20%EC%9B%A8%EC%95%84'
res = requests.get(url)
soup = BeautifulSoup(res.text,'lxml')
title = soup.find('a',{'class':'J23-5aq4'}).get_text(strip=True)
category = soup.find('ul',{'class':'EVpyuXop'}).get_text(strip=True)
content = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'}).get_text(strip=True)

In [7]:
data = []
for url in df['url'].head(50):
    # # 2. selenium : 자동화 도구 - 스크롤없이 가져옴
    # namu_url = url
    # options = Options()
    # options.add_experimental_option("excludeSwitches", ["enable-automation"])
    # options.add_experimental_option("useAutomationExtension", False)
    # options.add_argument("--disable-blink-features=AutomationControlled")
    # browser = webdriver.Chrome(options=options)
    # browser.maximize_window() # 화면 최대창 확대
    # browser.get(namu_url)
    # time.sleep(2)
    res = requests.get(url)
    time.sleep(1)
    soup = BeautifulSoup(res.text,'lxml')
    title_tag = soup.find('a',{'class':'J23-5aq4'})
    title = title_tag.get_text(strip=True) if title_tag else None
    category_tag = soup.find('ul',{'class':'EVpyuXop'})
    category = category_tag.get_text(strip=True) if category_tag else None
    content_tag = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'})
    content = content_tag.get_text(strip=True) if content_tag else None
    data.append({
        'title':title,
        'category':category,
        'content':content
    })

print('완료')


# # # 파일저장
# soup = BeautifulSoup(browser.page_source,'lxml')
# with open('file/namu_con1.html','w',encoding='utf-8') as f:
#     f.write(soup.prettify())

완료

In [8]:
n_df=pd.DataFrame(data)
n_df.to_csv('file/namu2.csv')
n_df

,title,category,content
0,조지 웨아,1966년 출생1981년 데뷔2003년 은퇴2018년 은퇴라이베리아 대통령라이베리아...,라이베리아 공화국 대통령[ 펼치기 · 접기 ]초대제2대제3대제4대조셉 젠킨스 로버츠...
1,경지,경지나무위키 웹소설 프로젝트무공칭호(무협),경계선 지능의 줄임말에 대한 내용은경계선 지능문서를 참고하십시오.보드게임 '벚꽃 내...
2,군산 버스 19,군산시의 시내버스,군산시시내버스 노선[ 펼치기 · 접기 ]미성동010203070809옥구읍111213...
3,House 2,2026년 Windows 게임미국 게임액션 어드벤처 게임호러 게임,하우스 2House 2개발Bark Bark Games유통Glowstick Enter...
4,장갑기병 보톰즈 회색의 마녀,보톰즈 시리즈일본 애니메이션/목록2026년 애니메이션 영화2026년 4분기 일본 애...,로도스도 전기에 등장하는 '회색의 마녀'에 대한 내용은칼라(포세리아)문서를 참고하십...
5,카드 앙 시엘/카드/드로,인티 크리에이츠카드 앙 시엘카드 앙 시엘/카드,카드 앙 시엘 카드 목록0코스트3코스트드로디버그리부트무브메모리 리크변신브레이크 포인...
6,사용자:SamSara,NaN,NaN
7,제단(워크래프트 3),워크래프트 3/건물,1. 개요2. 시스템3. 종류4. 여담Altar1.개요[편집]워크래프트 3의 종족 ...
8,빅 미키,토마스와 친구들/등장인물TUGS/등장인물1989년 창조된 캐릭터,크레인들[ 펼치기 · 접기 ]노스 웨스턴 철도 소속크랭키칼리빅 미키레지테스협궤 철도...
9,제임스 로니,1984년 출생2006년 데뷔2019년 은퇴미국의 야구 선수휴스턴 출신 인물외국인 ...,제임스 로니 관련 틀[ 펼치기 · 접기 ]로스앤젤레스 다저스역대 1라운드 지명선수[...
10,제25보병사단 DMZ 지뢰 폭발 사건,이재명 정부/사건사고/2026년대한민국 육군/사건 사고지뢰제25보병사단김정은 시대연...,한시적 넘겨주기로 연결되는 다른 문서에 대한 내용은 아래 문서를 참고하십시오.9월 ...
11,탱킹,스포츠 용어,MMORPG에서의 탱킹에 대한 내용은탱커문서를 참고하십시오.1. 개요2. 의도 및 ...
12,와다,성씨/일본,1. 개요2. 실존 인물3. 가상 인물1.개요[편집]わだ2015년 기준 和田는 42...
13,NaN,NaN,NaN
14,NaN,NaN,NaN
15,명탐정 코난: 시한장치의 마천루,명탐정 코난(애니메이션)/극장판일본 애니메이션/목록1997년 애니메이션 영화1997...,극장판[ 펼치기 · 접기 ]1기2기3기4기5기시한장치의 마천루(줄거리/쿠키 영상)1...
16,제단(워크래프트 3),워크래프트 3/건물,1. 개요2. 시스템3. 종류4. 여담Altar1.개요[편집]워크래프트 3의 종족 ...
17,영천시/정치,영천시경상북도의 정치,상위 문서:영천시관련 문서:영천시·청도군경상북도정치[ 펼치기 · 접기 ]경산시경주시...
18,극장판 이나즈마 일레븐 최강군단 오우거의 습격,이나즈마 일레븐 시리즈/애니메이션일본 애니메이션/목록2010년 애니메이션 영화일본의...,[ 펼치기 · 접기 ]무인 시리즈(애니메이션)이나즈마 일레븐이나즈마 일레븐 RE이나...
19,NaN,NaN,NaN
20,1991년 이라크 봉기,아시아의 봉기1991년 정치바트주의 이라크의 전쟁 및 전투사담 후세인이란-이라크 관...,1991년 이라크 봉기1991 Iraqi uprisings반군에 의해 파괴된 이라크...
21,2003 쇼트트랙 스피드 스케이팅 유럽선수권 대회,쇼트트랙 스피드 스케이팅 유럽선수권 대회,←2001-02ISU 쇼트트랙 스피드 스케이팅 2002-03 시즌2003-04→[ ...
22,불꽃 파이터즈/역대 전적/2026 시즌/경기 목록,불꽃야구2026년 야구2026년 방송 프로그램,상위 문서:불꽃 파이터즈/역대 전적/2026 시즌1. 개요1.1. 시즌 포맷 변경점...
23,흑색왜성,왜성(천체)가설상의 천체,편집 보호된 문서입니다. 문서의ACL 탭을 확인하세요.항성의진화[ 펼치기 · 접기 ...
24,NaN,NaN,NaN
25,김환희/골 때리는 그녀들/클럽 경력,FC 액셔니스타/현역,상위 문서:김환희/골 때리는 그녀들1. 개요2. 클럽2.1.FC 액셔니스타1.개요[...
26,NaN,NaN,NaN
27,사용자:Hexy_Joe/빠른 이동 및 연습장,NaN,NaN
28,난칸마치,구마모토현의 정1957년 설치된 행정구역,구마모토현시정촌[ 펼치기 · 접기 ]정령지정도시현청정령구마모토시(▶ 하위 행정구역)...
29,NaN,NaN,NaN
30,손무,몰년 미상춘추전국시대 및 진나라(영성)의 철학자둥잉시 출신 인물군사학자,손자(인물)은(는) 여기로 연결됩니다. 제(齊)나라의 손자(孫子)에 대한 내용은손빈...
31,FSO 폴로네즈,FSO/생산차량1978년 출시된 자동차2002년 단종된 자동차중형 해치백중형 왜건그룹 4,Polonez[1]1. 개요2. 배경 및 개발3. 출시 및 생산3.1. 폴로네즈(1...
32,2002 쇼트트랙 스피드 스케이팅 유럽선수권 대회,쇼트트랙 스피드 스케이팅 유럽선수권 대회,←2000-01ISU 쇼트트랙 스피드 스케이팅 2001-02 시즌2002-03→[ ...
33,PC정비사,컴퓨터정보통신자격면허,(사)한국정보평가협회(KIE)가 운영하는 국가공인민간자격증에 대한 내용은PC Mas...
34,불꽃 파이터즈/역대 전적/2026 시즌/경기 목록,불꽃야구2026년 야구2026년 방송 프로그램,상위 문서:불꽃 파이터즈/역대 전적/2026 시즌1. 개요1.1. 시즌 포맷 변경점...
35,분류:바트주의 이라크의 전쟁 및 전투,바트주의 이라크이라크의 전쟁 및 전투,
36,김환희/골 때리는 그녀들/클럽 경력/FC 액셔니스타,FC 액셔니스타/현역,상위 문서:김환희/골 때리는 그녀들/클럽 경력김환희시즌 8-소속 팀FC 액셔니스타소...
37,안양 정관장 레드부스터스,안양 정관장 레드부스터스한국인삼공사안양시 연고 구단대한민국의 프로 농구단한국프로농구...,2026-27 시즌에 대한 내용은안양 정관장 레드부스터스/2026-27 시즌문서를 ...
38,잔스파인/SD건담 지 제네레이션 이터널/UR,SD건담 지 제네레이션 이터널/유닛G제네레이션 시리즈/오리지널 기체베스파의 모빌슈트,"다른 지 제네레이션 시리즈에서의 잔스파인에 대한 내용은잔스파인문서를, 원작의 파라 ..."
39,사용자:SamSara,NaN,NaN
40,부산 OK저축은행 읏맨,부산 OK저축은행 읏맨OK금융그룹부산광역시 연고 구단연고지 이전대한민국의 프로 배구...,2026-27 시즌에 대한 내용은부산 OK저축은행 읏맨/2026-27 시즌문서를 참...
41,NaN,NaN,NaN
42,NaN,NaN,NaN
43,토오사카 린/작중 행적/본편,Fate 시리즈/캐릭터/작중 행적토오사카 린,상위 문서:토오사카 린/작중 행적이 문서에스포일러가 포함되어 있습니다.이 문서가 설...
44,김주성(야구선수)/선수 경력,대한민국의 야구 선수/경력,상위 문서:김주성(야구선수)1. 개요2. 아마추어 시절3.LG 트윈스3.1. 201...
45,리그 오브 레전드/증강/프리즘,리그 오브 레전드/증강,상위 문서:리그 오브 레전드/증강리그 오브 레전드의증강실버골드프리즘1. 개요2. 공...
46,조지 웨아,1966년 출생1981년 데뷔2003년 은퇴2018년 은퇴라이베리아 대통령라이베리아...,라이베리아 공화국 대통령[ 펼치기 · 접기 ]초대제2대제3대제4대조셉 젠킨스 로버츠...
47,사용자:Wpdl,NaN,NaN
48,아스파르,고트족동음이의어동로마 제국의 군인동로마의 섭정400년 출생471년 사망고대 로마의 ...,프린세스 메이커 5의 인물에 대한 내용은아스파르(프린세스 메이커 5)문서를 참고하십...
49,2025년/사건,2025년/사건사고,상위 문서:2025년연도별 사건 문서 바로가기2025년 사건←2024년 사건2026...